import { Practice, PracticeCategory } from './types';

export const practices: Practice[] = [
  // ─── MVP PACK (12 practices) ───────────────────────────────────────────────
  {
    id: 'long-exhale-reset',
    title: 'Long Exhale Reset',
    subtitle: 'Calm the body with longer exhales',
    description: 'A short breathing reset built around making the exhale slightly longer than the inhale. Useful when the body feels activated, rushed, tense, or overstimulated.',
    category: 'breath',
    durationSec: 120,
    intensity: 'low',
    useCases: ['anxiety', 'workStress', 'quickReset'],
    tags: ['breath', 'calm', 'quick'],
    safetyNote: 'If you feel dizzy or uncomfortable, stop controlling the breath and return to normal breathing.',
    beforePrompt: 'Notice your current stress level before starting.',
    afterPrompt: 'Notice whether anything feels even slightly different.',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    breathPattern: { inhaleSec: 4, exhaleSec: 6, cycles: 10 },
    pack: 'mvp',
    steps: [
      { id: 'lon-1', title: 'Settle', instruction: 'Sit or stand in a comfortable position. Let your shoulders drop slightly. You do not need to breathe perfectly.', durationSec: 15, phase: 'intro' },
      { id: 'lon-2', title: 'Notice', instruction: 'Notice your current breath without changing it yet.', durationSec: 15, phase: 'notice' },
      { id: 'lon-3', title: 'Inhale', instruction: 'Inhale softly for 4 seconds.', durationSec: 20, phase: 'inhale' },
      { id: 'lon-4', title: 'Exhale', instruction: 'Exhale slowly for 6 seconds.', durationSec: 25, phase: 'exhale' },
      { id: 'lon-5', title: 'Repeat', instruction: 'Continue with a soft 4-second inhale and a longer 6-second exhale.', durationSec: 30, phase: 'inhale' },
      { id: 'lon-6', title: 'Release', instruction: 'Let the next exhale be a little slower, without forcing it.', durationSec: 10, phase: 'release' },
      { id: 'lon-7', title: 'Complete', instruction: 'Return to natural breathing. Notice whether anything feels even slightly different.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'cyclic-sigh',
    title: 'Cyclic Sigh',
    subtitle: 'Double inhale, long exhale',
    description: 'A short stress reset using a double inhale followed by a long slow exhale. May help when the body feels activated or tense. Keep it gentle.',
    category: 'breath',
    durationSec: 90,
    intensity: 'low',
    useCases: ['anger', 'anxiety', 'quickReset'],
    tags: ['breath', 'calm', 'fast'],
    safetyNote: 'If you feel light-headed, return to normal breathing immediately.',
    beforePrompt: 'Notice the level of activation in your body right now.',
    afterPrompt: 'Check in — has anything shifted even slightly?',
    fallbackPracticeId: 'long-exhale-reset',
    breathPattern: { inhaleSec: 3, exhaleSec: 6, holdAfterInhaleSec: 1, cycles: 8 },
    pack: 'mvp',
    steps: [
      { id: 'cyc-1', title: 'Settle', instruction: 'Find a comfortable position. Shoulders relaxed.', durationSec: 10, phase: 'intro' },
      { id: 'cyc-2', title: 'First inhale', instruction: 'Inhale deeply through your nose.', durationSec: 10, phase: 'inhale' },
      { id: 'cyc-3', title: 'Second inhale', instruction: 'At the top of that inhale, sip in a little more air through the nose.', durationSec: 5, phase: 'inhale' },
      { id: 'cyc-4', title: 'Long exhale', instruction: 'Exhale slowly and fully through your mouth.', durationSec: 15, phase: 'exhale' },
      { id: 'cyc-5', title: 'Repeat cycle', instruction: 'Double inhale through nose, long exhale through mouth. Repeat at your own pace.', durationSec: 35, phase: 'inhale' },
      { id: 'cyc-6', title: 'Final exhale', instruction: 'One last long exhale. Let your breathing return to normal.', durationSec: 10, phase: 'exhale' },
      { id: 'cyc-7', title: 'Complete', instruction: 'Sit with whatever you notice. No need to label it.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    subtitle: 'Equal inhale, hold, exhale, hold',
    description: 'A structured breathing practice using equal inhale, hold, exhale, and pause phases. Useful before work, meetings, or focused tasks.',
    category: 'breath',
    durationSec: 180,
    intensity: 'low',
    useCases: ['focus', 'anxiety', 'workStress'],
    tags: ['breath', 'focus', 'structured'],
    safetyNote: 'If holding the breath causes discomfort, shorten the hold or skip it entirely.',
    beforePrompt: 'Rate your mental clarity right now.',
    afterPrompt: 'Notice if your mind feels any clearer or calmer.',
    fallbackPracticeId: 'long-exhale-reset',
    breathPattern: { inhaleSec: 4, exhaleSec: 4, holdAfterInhaleSec: 4, holdAfterExhaleSec: 4, cycles: 8 },
    pack: 'mvp',
    steps: [
      { id: 'box-1', title: 'Settle', instruction: 'Sit upright. Rest your hands. Close your eyes if comfortable.', durationSec: 15, phase: 'intro' },
      { id: 'box-2', title: 'Inhale', instruction: 'Inhale through the nose for 4 seconds.', durationSec: 20, phase: 'inhale' },
      { id: 'box-3', title: 'Hold', instruction: 'Hold your breath gently for 4 seconds.', durationSec: 20, phase: 'hold' },
      { id: 'box-4', title: 'Exhale', instruction: 'Exhale through the mouth for 4 seconds.', durationSec: 20, phase: 'exhale' },
      { id: 'box-5', title: 'Hold', instruction: 'Hold at the bottom for 4 seconds.', durationSec: 20, phase: 'pause' },
      { id: 'box-6', title: 'Continue', instruction: 'Repeat the box: inhale 4, hold 4, exhale 4, hold 4. Find a steady rhythm.', durationSec: 70, phase: 'inhale' },
      { id: 'box-7', title: 'Complete', instruction: 'Release the pattern. Breathe naturally. Notice your state.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'five-four-three-two-one-grounding',
    title: '5-4-3-2-1 Grounding',
    subtitle: 'Engage all five senses',
    description: 'A classic grounding technique that uses sensory engagement to bring attention out of spiraling thoughts and back into the present moment. Effective for anxiety, dissociation, and panic.',
    category: 'grounding',
    durationSec: 150,
    intensity: 'low',
    useCases: ['anxiety', 'panicLite', 'numb', 'overthinking'],
    tags: ['grounding', 'senses', 'panic'],
    beforePrompt: 'Notice how disconnected or overwhelmed you feel.',
    afterPrompt: 'Check — do you feel even slightly more present?',
    fallbackPracticeId: 'feet-on-floor',
    pack: 'mvp',
    steps: [
      { id: 'fiv-1', title: 'Settle', instruction: 'Pause wherever you are. You do not need to move or change anything.', durationSec: 10, phase: 'intro' },
      { id: 'fiv-2', title: '5 things you see', instruction: 'Look around and silently name 5 things you can see right now.', durationSec: 30, phase: 'orient' },
      { id: 'fiv-3', title: '4 things you can touch', instruction: 'Notice 4 things you can physically feel — texture, temperature, pressure.', durationSec: 25, phase: 'notice' },
      { id: 'fiv-4', title: '3 things you hear', instruction: 'Listen for 3 sounds. Near or far, loud or quiet.', durationSec: 25, phase: 'notice' },
      { id: 'fiv-5', title: '2 things you smell', instruction: 'Notice 2 scents. If nothing is obvious, bring something close to your nose.', durationSec: 25, phase: 'notice' },
      { id: 'fiv-6', title: '1 thing you taste', instruction: 'Notice 1 taste in your mouth right now.', durationSec: 20, phase: 'notice' },
      { id: 'fiv-7', title: 'Complete', instruction: 'Take a breath. You are here, in this moment.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'feet-on-floor',
    title: 'Feet on Floor',
    subtitle: 'Ground through body contact',
    description: 'A minimal grounding practice focused on physical contact between your feet and the ground. Quick, effective, and works anywhere — sitting or standing.',
    category: 'grounding',
    durationSec: 60,
    intensity: 'low',
    useCases: ['panicLite', 'numb', 'quickReset'],
    tags: ['grounding', 'quick', 'body'],
    beforePrompt: 'Notice how present or disconnected you feel.',
    afterPrompt: 'Do you feel even slightly more grounded?',
    fallbackPracticeId: 'room-orientation',
    pack: 'mvp',
    steps: [
      { id: 'fee-1', title: 'Notice', instruction: 'Feel both feet making contact with the floor or ground beneath you.', durationSec: 10, phase: 'notice', voiceCue: 'Feel both feet on the floor.' },
      { id: 'fee-2', title: 'Press', instruction: 'Press your feet down gently. Notice the pressure and texture.', durationSec: 15, phase: 'press', haptic: true, voiceCue: 'Press your feet down gently.' },
      { id: 'fee-3', title: 'Lift and press', instruction: 'Lift your toes, then press them back down. Notice the shift.', durationSec: 15, phase: 'press', voiceCue: 'Lift your toes, then press them back down.' },
      { id: 'fee-4', title: 'Rock', instruction: 'Gently shift your weight side to side. Feel the ground supporting you.', durationSec: 10, phase: 'notice', voiceCue: 'Rock your weight side to side.' },
      { id: 'fee-5', title: 'Complete', instruction: 'Stand or sit still. You are here. The ground is holding you.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'room-orientation',
    title: 'Room Orientation',
    subtitle: 'Look around slowly and notice',
    description: 'A slow orientation practice that uses the eyes, head, and environment to reduce inner tunnel vision. May help when feeling disconnected or stuck in thought loops.',
    category: 'grounding',
    durationSec: 90,
    intensity: 'low',
    useCases: ['panicLite', 'numb', 'overthinking', 'shame'],
    tags: ['grounding', 'orienting', 'presence'],
    beforePrompt: 'Notice how trapped or disconnected you feel.',
    afterPrompt: 'Has your sense of the room around you shifted at all?',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    pack: 'mvp',
    steps: [
      { id: 'roo-1', title: 'Pause', instruction: 'Wherever you are, stop and let your eyes rest somewhere neutral.', durationSec: 10, phase: 'intro', voiceCue: 'Pause. Let your eyes rest.' },
      { id: 'roo-2', title: 'Look left', instruction: 'Slowly turn your head to the left. Notice what you see without labeling it.', durationSec: 15, phase: 'orient', voiceCue: 'Slowly look to the left.' },
      { id: 'roo-3', title: 'Look right', instruction: 'Now slowly turn your head to the right. Let your eyes land on objects, colors, textures.', durationSec: 15, phase: 'orient', voiceCue: 'Now slowly look to the right.' },
      { id: 'roo-4', title: 'Look up', instruction: 'Tilt your gaze upward. Notice the ceiling, sky, or whatever is above.', durationSec: 15, phase: 'orient', voiceCue: 'Look up. Notice what is above.' },
      { id: 'roo-5', title: 'Look down', instruction: 'Look toward the floor. Notice your feet, the ground, the surface.', durationSec: 15, phase: 'orient', voiceCue: 'Look down toward the floor.' },
      { id: 'roo-6', title: 'Choose one thing', instruction: 'Let your eyes settle on one object that feels neutral or pleasant. Stay with it for a few breaths.', durationSec: 15, phase: 'notice', voiceCue: 'Settle on one object. Stay with it.' },
      { id: 'roo-7', title: 'Complete', instruction: 'Notice where you are. This is the room around you.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'jaw-shoulders-release',
    title: 'Jaw & Shoulders Release',
    subtitle: 'Release stored tension in jaw and shoulders',
    description: 'A quick body-based release targeting the two most common tension-holding areas: jaw and shoulders. Uses intentional squeeze and release for fast relief.',
    category: 'body',
    durationSec: 90,
    intensity: 'low',
    useCases: ['bodyTension', 'anger', 'quickReset'],
    tags: ['body', 'tension', 'quick'],
    beforePrompt: 'Notice the tension level in your jaw and shoulders.',
    afterPrompt: 'Check — do your jaw and shoulders feel any different?',
    fallbackPracticeId: 'mini-pmr',
    pack: 'mvp',
    steps: [
      { id: 'jaw-1', title: 'Notice', instruction: 'Bring your attention to your jaw. Is it clenched? Tight? Holding?', durationSec: 10, phase: 'notice', voiceCue: 'Notice your jaw.' },
      { id: 'jaw-2', title: 'Squeeze jaw', instruction: 'Clench your jaw deliberately for 5 seconds. Feel the tension.', durationSec: 10, phase: 'press', haptic: true, voiceCue: 'Squeeze your jaw for five seconds.' },
      { id: 'jaw-3', title: 'Release jaw', instruction: 'Let your jaw fall open slightly. Let your tongue rest. Breathe.', durationSec: 15, phase: 'release', voiceCue: 'Release. Let your jaw fall open.' },
      { id: 'jaw-4', title: 'Notice shoulders', instruction: 'Bring attention to your shoulders. Are they raised? Tight?', durationSec: 10, phase: 'notice', voiceCue: 'Notice your shoulders.' },
      { id: 'jaw-5', title: 'Squeeze shoulders', instruction: 'Raise your shoulders toward your ears. Hold for 5 seconds.', durationSec: 10, phase: 'press', haptic: true, voiceCue: 'Shoulders up to your ears. Hold.' },
      { id: 'jaw-6', title: 'Release shoulders', instruction: 'Drop your shoulders completely. Let them fall with gravity.', durationSec: 15, phase: 'release', voiceCue: 'Let your shoulders drop.' },
      { id: 'jaw-7', title: 'Breathe', instruction: 'Take one slow breath with jaw soft and shoulders low.', durationSec: 15, phase: 'exhale', voiceCue: 'One slow breath. Jaw soft, shoulders low.' },
      { id: 'jaw-8', title: 'Complete', instruction: 'Notice the difference. Even a small shift counts.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'soft-belly-breathing',
    title: 'Soft Belly Breathing',
    subtitle: 'Gentle awareness of the breath in the belly',
    description: 'A calm breathing practice that helps shift attention from effort and control into softer body awareness.',
    category: 'breath',
    durationSec: 300,
    intensity: 'low',
    useCases: ['anxiety', 'burnout', 'sleep', 'quickReset'],
    tags: ['breath', 'gentle', 'body-awareness'],
    safetyNote: 'Do not force deep breathing. Let the breath stay comfortable.',
    beforePrompt: 'Notice how much effort you are putting into breathing.',
    afterPrompt: 'Notice if your breath feels any softer.',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    breathPattern: { inhaleSec: 4, exhaleSec: 6, cycles: 20 },
    pack: 'mvp',
    steps: [
      { id: 'sbb-1', title: 'Place hand', instruction: 'Place one hand on your chest and one hand on your belly if comfortable.', durationSec: 30, phase: 'intro', voiceCue: 'One hand on chest, one on belly.' },
      { id: 'sbb-2', title: 'Notice', instruction: 'Notice where the breath naturally moves.', durationSec: 30, phase: 'notice', voiceCue: 'Notice where the breath moves.' },
      { id: 'sbb-3', title: 'Soften', instruction: 'Let the belly be soft. No need to push it out.', durationSec: 40, phase: 'release', voiceCue: 'Let the belly be soft.' },
      { id: 'sbb-4', title: 'Inhale', instruction: 'Inhale gently and notice the hands.', durationSec: 60, phase: 'inhale', voiceCue: 'Inhale gently. Notice the hands.' },
      { id: 'sbb-5', title: 'Exhale', instruction: 'Exhale gently and let effort drop.', durationSec: 60, phase: 'exhale', voiceCue: 'Exhale. Let effort drop.' },
      { id: 'sbb-6', title: 'Return', instruction: 'If the mind wanders, return to the feeling of the hands.', durationSec: 60, phase: 'notice', voiceCue: 'Return to the feeling of the hands.' },
      { id: 'sbb-7', title: 'Complete', instruction: 'Let the breath become natural again.', durationSec: 20, phase: 'complete' },
    ],
  },
  {
    id: 'mini-pmr',
    title: 'Mini Progressive Muscle Relaxation',
    subtitle: 'Tense and release through body groups',
    description: 'A shortened version of progressive muscle relaxation. Moves through fists, arms, shoulders, and face — squeezing and releasing each group to discharge tension.',
    category: 'body',
    durationSec: 180,
    intensity: 'medium',
    useCases: ['bodyTension', 'anxiety', 'sleep'],
    tags: ['body', 'relaxation', 'tension-release'],
    beforePrompt: 'Notice where tension lives in your body right now.',
    afterPrompt: 'Scan your body — has anything softened?',
    fallbackPracticeId: 'jaw-shoulders-release',
    pack: 'mvp',
    steps: [
      { id: 'min-1', title: 'Settle', instruction: 'Sit or lie down comfortably. Close your eyes if you want.', durationSec: 15, phase: 'intro', voiceCue: 'Get comfortable. Close your eyes if you like.' },
      { id: 'min-2', title: 'Fists — squeeze', instruction: 'Make fists with both hands. Squeeze them tightly for 5 seconds.', durationSec: 15, phase: 'press', haptic: true, voiceCue: 'Make fists. Squeeze tight.' },
      { id: 'min-3', title: 'Fists — release', instruction: 'Open your hands slowly. Notice the contrast — the warmth, the ease.', durationSec: 20, phase: 'release', voiceCue: 'Open your hands. Notice the warmth.' },
      { id: 'min-4', title: 'Arms — squeeze', instruction: 'Tense your arms — biceps, forearms. Hold for 5 seconds.', durationSec: 15, phase: 'press', haptic: true, voiceCue: 'Tense your arms. Hold.' },
      { id: 'min-5', title: 'Arms — release', instruction: 'Let your arms go limp. Feel the release spreading.', durationSec: 20, phase: 'release', voiceCue: 'Let your arms go limp.' },
      { id: 'min-6', title: 'Shoulders — squeeze', instruction: 'Raise shoulders to ears. Squeeze. Hold for 5 seconds.', durationSec: 15, phase: 'press', haptic: true, voiceCue: 'Shoulders up. Squeeze and hold.' },
      { id: 'min-7', title: 'Shoulders — release', instruction: 'Drop them. Let gravity take them. Breathe out.', durationSec: 20, phase: 'release', voiceCue: 'Drop them. Breathe out.' },
      { id: 'min-8', title: 'Face — squeeze', instruction: 'Scrunch your whole face — eyes, mouth, forehead. Hold.', durationSec: 15, phase: 'press', voiceCue: 'Scrunch your face. Hold.' },
      { id: 'min-9', title: 'Face — release', instruction: 'Soften everything. Smooth forehead, soft eyes, relaxed mouth.', durationSec: 20, phase: 'release', voiceCue: 'Soften everything. Smooth and soft.' },
      { id: 'min-10', title: 'Complete', instruction: 'Breathe naturally. Notice your body as a whole — lighter, softer, different.', durationSec: 25, phase: 'complete' },
    ],
  },
  {
    id: 'sixty-second-body-check',
    title: '60-Second Body Check',
    subtitle: 'Quick scan to notice what you need',
    description: 'A fast body scan for moments when you do not know what you need. Notice what is present without fixing it.',
    category: 'body',
    durationSec: 60,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy', 'anxiety', 'quickReset', 'workStress'],
    tags: ['body', 'scan', 'quick', 'routing'],
    safetyNote: 'If body awareness feels uncomfortable, switch to Room Orientation.',
    beforePrompt: 'Notice what drew you to open this practice.',
    afterPrompt: 'What did you notice? Choose what you need next.',
    fallbackPracticeId: 'room-orientation',
    pack: 'mvp',
    steps: [
      { id: 'sbc-1', title: 'Breath', instruction: 'Notice your breath. Fast, slow, shallow, or neutral?', durationSec: 10, phase: 'notice', voiceCue: 'Notice your breath.' },
      { id: 'sbc-2', title: 'Jaw', instruction: 'Notice your jaw. Tight or soft?', durationSec: 8, phase: 'notice', voiceCue: 'Notice your jaw.' },
      { id: 'sbc-3', title: 'Shoulders', instruction: 'Notice your shoulders. Lifted or dropped?', durationSec: 8, phase: 'notice', voiceCue: 'Notice your shoulders.' },
      { id: 'sbc-4', title: 'Chest', instruction: 'Notice your chest. Open, tight, heavy, or neutral?', durationSec: 8, phase: 'notice', voiceCue: 'Notice your chest.' },
      { id: 'sbc-5', title: 'Belly', instruction: 'Notice your belly. Braced, soft, tense, or neutral?', durationSec: 8, phase: 'notice', voiceCue: 'Notice your belly.' },
      { id: 'sbc-6', title: 'Hands', instruction: 'Notice your hands. Warm, cold, clenched, relaxed?', durationSec: 8, phase: 'notice', voiceCue: 'Notice your hands.' },
      { id: 'sbc-7', title: 'Choose', instruction: 'Pick what you need next: breathe, release, ground, rest, or focus.', durationSec: 10, phase: 'complete', voiceCue: 'Pick what you need next.' },
    ],
  },
  {
    id: 'sleep-exhale',
    title: 'Sleep Exhale',
    subtitle: 'Long exhales to ease into sleep',
    description: 'A bedtime breathing practice using progressively longer exhales to activate the parasympathetic nervous system and prepare the body for sleep.',
    category: 'sleep',
    durationSec: 180,
    intensity: 'low',
    useCases: ['sleep', 'anxiety'],
    tags: ['sleep', 'breath', 'bedtime', 'parasympathetic'],
    safetyNote: 'If controlling the breath feels uncomfortable, return to natural breathing.',
    beforePrompt: 'How awake or activated does your body feel?',
    afterPrompt: 'Does your body feel any heavier or sleepier?',
    fallbackPracticeId: 'body-heavy',
    pack: 'mvp',
    steps: [
      { id: 'sle-1', title: 'Position', instruction: 'Lie down or recline. Close your eyes. Let your body be heavy.', durationSec: 15, phase: 'intro', voiceCue: 'Lie down. Close your eyes.' },
      { id: 'sle-2', title: 'Natural breath', instruction: 'Breathe naturally for a few breaths. No control yet.', durationSec: 20, phase: 'notice', voiceCue: 'Breathe naturally. No control yet.' },
      { id: 'sle-3', title: 'Inhale 4', instruction: 'Inhale softly for 4 seconds.', durationSec: 15, phase: 'inhale', voiceCue: 'Inhale for four seconds.' },
      { id: 'sle-4', title: 'Exhale 6', instruction: 'Exhale slowly for 6 seconds. Let the exhale be soft and complete.', durationSec: 20, phase: 'exhale', voiceCue: 'Exhale for six seconds. Soft and slow.' },
      { id: 'sle-5', title: 'Inhale 4', instruction: 'Inhale for 4 seconds again. Gentle and easy.', durationSec: 15, phase: 'inhale', voiceCue: 'Inhale for four. Gentle and easy.' },
      { id: 'sle-6', title: 'Exhale 8', instruction: 'Now extend the exhale to 8 seconds. Slow, like a deflating balloon.', durationSec: 25, phase: 'exhale', voiceCue: 'Exhale for eight seconds. Slow.' },
      { id: 'sle-7', title: 'Continue', instruction: 'Continue with inhale 4, exhale 8. Let each exhale pull you deeper into rest.', durationSec: 50, phase: 'exhale', voiceCue: 'Inhale four, exhale eight. Keep going.' },
      { id: 'sle-8', title: 'Complete', instruction: 'Release the pattern. Let the body rest without forcing sleep.', durationSec: 20, phase: 'complete' },
    ],
  },
  {
    id: 'notice-the-thought',
    title: 'Notice the Thought',
    subtitle: 'Observe thoughts without engaging',
    description: 'A mindfulness micro-practice for thought loops and overthinking. Not about stopping thoughts — just about noticing them as events rather than facts.',
    category: 'mindfulness',
    durationSec: 120,
    intensity: 'low',
    useCases: ['overthinking', 'anxiety', 'shame'],
    tags: ['mindfulness', 'thoughts', 'observe'],
    beforePrompt: 'Notice how loud or fast your thoughts feel right now.',
    afterPrompt: 'Did any space open up between you and your thoughts?',
    fallbackPracticeId: 'room-orientation',
    pack: 'mvp',
    steps: [
      { id: 'not-1', title: 'Settle', instruction: 'Sit still for a moment. You do not need to fix or solve anything right now.', durationSec: 15, phase: 'intro' },
      { id: 'not-2', title: 'Notice', instruction: 'Notice that thoughts are happening. Just acknowledge: "There is a thought."', durationSec: 20, phase: 'notice' },
      { id: 'not-3', title: 'Label', instruction: 'If you can, gently label the thought: planning, worrying, remembering, judging.', durationSec: 20, phase: 'reflect' },
      { id: 'not-4', title: 'Let it pass', instruction: 'Imagine the thought as a cloud passing. You do not need to chase it.', durationSec: 25, phase: 'reflect' },
      { id: 'not-5', title: 'Return', instruction: 'When you get pulled into a thought, gently return to noticing. No judgment.', durationSec: 25, phase: 'notice' },
      { id: 'not-6', title: 'Complete', instruction: 'You are not your thoughts. They come and go. You can just watch.', durationSec: 15, phase: 'complete' },
    ],
  },

  // ─── WORKDAY PACK (5 practices) ─────────────────────────────────────────────
  {
    id: 'before-meeting-reset',
    title: 'Before Meeting Reset',
    subtitle: 'Quick reset before a stressful meeting',
    description: 'A 90-second practice designed for the gap between meetings or before a difficult conversation. Combines breath and body awareness to shift from reactive to present.',
    category: 'workday',
    durationSec: 90,
    intensity: 'low',
    useCases: ['workStress', 'focus', 'anxiety'],
    tags: ['workday', 'meetings', 'quick'],
    beforePrompt: 'Notice your level of dread or tension about the upcoming situation.',
    afterPrompt: 'Do you feel even slightly more ready?',
    fallbackPracticeId: 'long-exhale-reset',
    pack: 'workday',
    steps: [
      { id: 'bef-1', title: 'Pause', instruction: 'Before you join, pause. Close your laptop or put your phone face-down for a moment.', durationSec: 10, phase: 'intro' },
      { id: 'bef-2', title: 'Feet', instruction: 'Feel your feet on the floor. Press them down once.', durationSec: 10, phase: 'press' },
      { id: 'bef-3', title: 'Exhale', instruction: 'Take one long exhale. Let it be slow and complete.', durationSec: 15, phase: 'exhale' },
      { id: 'bef-4', title: 'Shoulders', instruction: 'Drop your shoulders. Unclench your jaw.', durationSec: 10, phase: 'release' },
      { id: 'bef-5', title: 'Intention', instruction: 'Ask yourself: what do I need from this meeting? Let one word come.', durationSec: 20, phase: 'reflect' },
      { id: 'bef-6', title: 'Breathe', instruction: 'One more slow breath. Inhale presence. Exhale tension.', durationSec: 15, phase: 'exhale' },
      { id: 'bef-7', title: 'Complete', instruction: 'You are as ready as you need to be. Go.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'after-conflict-reset',
    title: 'After Conflict Reset',
    subtitle: 'Decompress after tension or criticism',
    description: 'A decompression practice after tension, conflict, criticism, or a stressful conversation.',
    category: 'workday',
    durationSec: 180,
    intensity: 'medium',
    useCases: ['anger', 'workStress', 'anxiety'],
    tags: ['workday', 'conflict', 'decompression'],
    safetyNote: 'Step away from the trigger if possible before starting.',
    beforePrompt: 'How activated do you feel after what happened?',
    afterPrompt: 'Has some of the charge released?',
    fallbackPracticeId: 'jaw-shoulders-release',
    pack: 'workday',
    steps: [
      { id: 'acr-1', title: 'Step away', instruction: 'Step away from the trigger if possible.', durationSec: 20, phase: 'intro' },
      { id: 'acr-2', title: 'Unclench', instruction: 'Unclench your jaw.', durationSec: 20, phase: 'release' },
      { id: 'acr-3', title: 'Press feet', instruction: 'Press your feet into the floor.', durationSec: 25, phase: 'press' },
      { id: 'acr-4', title: 'Exhale', instruction: 'Exhale slowly.', durationSec: 25, phase: 'exhale' },
      { id: 'acr-5', title: 'Name', instruction: 'Name what happened in one neutral sentence.', durationSec: 30, phase: 'reflect' },
      { id: 'acr-6', title: 'Notice', instruction: 'Notice what is still physically activated.', durationSec: 25, phase: 'notice' },
      { id: 'acr-7', title: 'Drop', instruction: 'Let your shoulders drop.', durationSec: 20, phase: 'release' },
      { id: 'acr-8', title: 'Choose', instruction: 'Choose whether you need action, rest, or space.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'desk-body-release',
    title: 'Desk Body Release',
    subtitle: 'Release tension from sitting',
    description: 'A body-focused practice designed for people who have been sitting too long. Targets neck, shoulders, wrists, and back without needing to stand.',
    category: 'workday',
    durationSec: 150,
    intensity: 'low',
    useCases: ['bodyTension', 'workStress'],
    tags: ['workday', 'body', 'desk', 'sitting'],
    beforePrompt: 'Notice where your body is holding tension from sitting.',
    afterPrompt: 'Does your body feel any different — even a little?',
    fallbackPracticeId: 'jaw-shoulders-release',
    pack: 'workday',
    steps: [
      { id: 'des-1', title: 'Notice', instruction: 'Without moving yet, scan your body. Where is the tension? Neck? Shoulders? Lower back?', durationSec: 15, phase: 'notice' },
      { id: 'des-2', title: 'Neck rolls', instruction: 'Slowly drop your chin to your chest, then roll your head gently to one side, then the other.', durationSec: 25, phase: 'release' },
      { id: 'des-3', title: 'Shoulder shrug', instruction: 'Raise both shoulders to your ears. Hold 3 seconds. Drop them completely.', durationSec: 20, phase: 'press' },
      { id: 'des-4', title: 'Wrist circles', instruction: 'Circle your wrists slowly — 5 times one way, 5 times the other.', durationSec: 20, phase: 'release' },
      { id: 'des-5', title: 'Spine twist', instruction: 'Sitting tall, gently twist your torso to the left, hold, then to the right.', durationSec: 25, phase: 'release' },
      { id: 'des-6', title: 'Hands press', instruction: 'Press your palms together in front of your chest firmly for 5 seconds, then release.', durationSec: 20, phase: 'press', haptic: true },
      { id: 'des-7', title: 'Settle', instruction: 'Sit back. Take one breath. Let your body settle into a slightly new position.', durationSec: 15, phase: 'release' },
      { id: 'des-8', title: 'Complete', instruction: 'Your body just got a small reset. That counts.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'eye-softening',
    title: 'Eye Softening',
    subtitle: 'Reset screen fatigue and mental strain',
    description: 'A short visual reset for screen fatigue and mental strain.',
    category: 'workday',
    durationSec: 120,
    intensity: 'low',
    useCases: ['focus', 'workStress', 'bodyTension'],
    tags: ['workday', 'eyes', 'screen', 'quick'],
    safetyNote: 'Move eyes gently. Do not strain.',
    beforePrompt: 'How tired do your eyes feel?',
    afterPrompt: 'Do your eyes feel any less fixed?',
    fallbackPracticeId: 'desk-body-release',
    pack: 'workday',
    steps: [
      { id: 'eys-1', title: 'Look away', instruction: 'Look away from the screen.', durationSec: 15, phase: 'intro' },
      { id: 'eys-2', title: 'Soften gaze', instruction: 'Soften your gaze.', durationSec: 20, phase: 'release' },
      { id: 'eys-3', title: 'Edges', instruction: 'Notice the edges of the room.', durationSec: 20, phase: 'orient' },
      { id: 'eys-4', title: 'Blink', instruction: 'Blink slowly.', durationSec: 15, phase: 'release' },
      { id: 'eys-5', title: 'Distance', instruction: 'Look at something farther away.', durationSec: 20, phase: 'orient' },
      { id: 'eys-6', title: 'Forehead', instruction: 'Relax your forehead.', durationSec: 15, phase: 'release' },
      { id: 'eys-7', title: 'Return', instruction: 'Return when your eyes feel less fixed.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'end-of-work-ritual',
    title: 'End of Work Ritual',
    subtitle: 'Separate work mode from personal time',
    description: 'A transition ritual to help separate work mode from personal time.',
    category: 'workday',
    durationSec: 300,
    intensity: 'low',
    useCases: ['workStress', 'burnout', 'sleep'],
    tags: ['workday', 'transition', 'ritual', 'evening'],
    safetyNote: 'This works best when done consistently at the same time.',
    beforePrompt: 'How much are you still carrying from work?',
    afterPrompt: 'Does work feel any more distant?',
    fallbackPracticeId: 'long-exhale-reset',
    pack: 'workday',
    steps: [
      { id: 'eow-1', title: 'Close', instruction: 'Close or minimize work tools if possible.', durationSec: 30, phase: 'intro' },
      { id: 'eow-2', title: 'Completed', instruction: 'Name one thing completed today.', durationSec: 40, phase: 'reflect' },
      { id: 'eow-3', title: 'Can wait', instruction: 'Name one thing that can wait.', durationSec: 40, phase: 'reflect' },
      { id: 'eow-4', title: 'Exhale', instruction: 'Exhale slowly.', durationSec: 40, phase: 'exhale' },
      { id: 'eow-5', title: 'Relax', instruction: 'Relax your jaw and shoulders.', durationSec: 40, phase: 'release' },
      { id: 'eow-6', title: 'Feet', instruction: 'Put attention on your feet.', durationSec: 40, phase: 'notice' },
      { id: 'eow-7', title: 'Done', instruction: 'Work is not finished forever. Work is finished for now.', durationSec: 70, phase: 'complete' },
    ],
  },

  // ─── EMOTIONAL PACK (5 practices) ──────────────────────────────────────────
  {
    id: 'anger-cooling',
    title: 'Anger Cooling',
    subtitle: 'Cool down hot anger without suppressing',
    description: 'A practice for when anger is running hot. Not about pushing it away — about giving it a channel to discharge safely without escalation.',
    category: 'emotional',
    durationSec: 120,
    intensity: 'medium',
    useCases: ['anger', 'bodyTension'],
    tags: ['emotional', 'anger', 'discharge', 'cooling'],
    safetyNote: 'This is not about suppressing anger. It is about not letting it drive your actions. If rage is overwhelming, walk away from the situation first.',
    beforePrompt: 'How hot does the anger feel right now?',
    afterPrompt: 'Has the temperature dropped even one degree?',
    fallbackPracticeId: 'cyclic-sigh',
    pack: 'emotional',
    steps: [
      { id: 'ang-1', title: 'Acknowledge', instruction: 'You are angry. That is real. You do not have to act on it right now.', durationSec: 10, phase: 'intro' },
      { id: 'ang-2', title: 'Hands', instruction: 'Press your palms flat on a surface — desk, wall, thighs. Press hard for 5 seconds.', durationSec: 15, phase: 'press', haptic: true },
      { id: 'ang-3', title: 'Release', instruction: 'Release the press. Shake your hands out loosely.', durationSec: 10, phase: 'release' },
      { id: 'ang-4', title: 'Cold breath', instruction: 'Breathe in through your nose. Exhale slowly through pursed lips — like blowing on hot soup.', durationSec: 20, phase: 'exhale' },
      { id: 'ang-5', title: 'Repeat', instruction: 'Again: press hard, release, shake, exhale through pursed lips.', durationSec: 25, phase: 'press' },
      { id: 'ang-6', title: 'Name it', instruction: 'Silently say: "I am angry about ___." Just name it. Do not solve it.', durationSec: 20, phase: 'reflect' },
      { id: 'ang-7', title: 'Ground', instruction: 'Feel your feet on the ground. You are here. The anger does not own you.', durationSec: 15, phase: 'notice' },
      { id: 'ang-8', title: 'Complete', instruction: 'You chose not to react. That takes strength. The anger will pass.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'shame-softening',
    title: 'Shame Softening',
    subtitle: 'Gently loosen the grip of shame',
    description: 'A practice for when shame or self-criticism is loud. Uses gentle awareness and self-compassion to create space around the feeling.',
    category: 'emotional',
    durationSec: 150,
    intensity: 'low',
    useCases: ['shame', 'sadness', 'overthinking'],
    tags: ['emotional', 'shame', 'self-compassion', 'softening'],
    safetyNote: 'Shame can feel overwhelming. If it becomes too intense, ground yourself with the 5-4-3-2-1 technique or reach out to someone you trust.',
    beforePrompt: 'How strong is the shame or self-criticism right now?',
    afterPrompt: 'Has the voice softened even a little?',
    fallbackPracticeId: 'room-orientation',
    pack: 'emotional',
    steps: [
      { id: 'sha-1', title: 'Notice', instruction: 'Notice the shame. Where does it live? What is it saying?', durationSec: 15, phase: 'notice' },
      { id: 'sha-2', title: 'Name it', instruction: 'Silently acknowledge: "This is shame." Naming it creates a tiny distance from it.', durationSec: 15, phase: 'reflect' },
      { id: 'sha-3', title: 'Body', instruction: 'Notice where shame lives in your body. Chest? Face? Stomach? Heat? Heaviness?', durationSec: 20, phase: 'notice' },
      { id: 'sha-4', title: 'Breathe toward it', instruction: 'Breathe gently toward that area. Not to fix — just to acknowledge.', durationSec: 20, phase: 'exhale' },
      { id: 'sha-5', title: 'Common humanity', instruction: 'Everyone has felt this. You are not alone in this feeling. It is human.', durationSec: 20, phase: 'reflect' },
      { id: 'sha-6', title: 'Kind word', instruction: 'Offer yourself one kind word or phrase: "I am doing my best." "I am worthy of kindness."', durationSec: 25, phase: 'reflect' },
      { id: 'sha-7', title: 'Hands', instruction: 'Place your hands somewhere comforting — heart, belly, arms crossed in a self-hug.', durationSec: 20, phase: 'press' },
      { id: 'sha-8', title: 'Complete', instruction: 'The shame does not define you. You showed up for yourself. That matters.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'sadness-grounding',
    title: 'Sadness Grounding',
    subtitle: 'Be with sadness without drowning',
    description: 'A gentle practice for when sadness is present. Not about fixing or fighting it — about being with it safely and knowing it will move.',
    category: 'emotional',
    durationSec: 150,
    intensity: 'low',
    useCases: ['sadness', 'numb', 'lowEnergy'],
    tags: ['emotional', 'sadness', 'gentle', 'grounding'],
    safetyNote: 'If sadness feels unbearable or you are having thoughts of self-harm, please reach out to a crisis helpline or trusted person.',
    beforePrompt: 'How heavy does the sadness feel?',
    afterPrompt: 'Is there any space around the sadness now?',
    fallbackPracticeId: 'feet-on-floor',
    pack: 'emotional',
    steps: [
      { id: 'sad-1', title: 'Acknowledge', instruction: 'Something hurts. You do not have to explain it or fix it right now.', durationSec: 15, phase: 'intro' },
      { id: 'sad-2', title: 'Body', instruction: 'Where do you feel the sadness in your body? Chest? Throat? Eyes? Just notice.', durationSec: 20, phase: 'notice' },
      { id: 'sad-3', title: 'Hand on heart', instruction: 'Place a hand on your chest if that feels okay. Feel the warmth of your own hand.', durationSec: 20, phase: 'press' },
      { id: 'sad-4', title: 'Breathe with it', instruction: 'Breathe gently. Not to fix the sadness — just to be with it.', durationSec: 25, phase: 'exhale' },
      { id: 'sad-5', title: 'Allow', instruction: 'Silently say: "It is okay to feel this." You do not need to be strong right now.', durationSec: 20, phase: 'reflect' },
      { id: 'sad-6', title: 'Anchor', instruction: 'Feel your feet on the ground. The ground is still here. You are still here.', durationSec: 20, phase: 'notice' },
      { id: 'sad-7', title: 'Kindness', instruction: 'What would you say to a friend feeling this? Offer that same kindness to yourself.', durationSec: 20, phase: 'reflect' },
      { id: 'sad-8', title: 'Complete', instruction: 'You stayed with it. That is brave. The sadness will move when it is ready.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'fear-naming',
    title: 'Fear Naming',
    subtitle: 'Name fear clearly instead of letting it stay vague',
    description: 'A practice for naming fear clearly instead of letting it remain a vague threat.',
    category: 'emotional',
    durationSec: 240,
    intensity: 'medium',
    useCases: ['anxiety', 'panicLite', 'overthinking'],
    tags: ['emotional', 'fear', 'naming', 'clarity'],
    safetyNote: 'If fear escalates, switch to grounding.',
    beforePrompt: 'How vague or consuming does the fear feel?',
    afterPrompt: 'Is the fear any clearer or smaller now?',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    pack: 'emotional',
    steps: [
      { id: 'fn-1', title: 'Notice', instruction: 'Notice that fear is present.', durationSec: 30, phase: 'notice' },
      { id: 'fn-2', title: 'Ask', instruction: 'Ask: "What is my body preparing for?"', durationSec: 40, phase: 'reflect' },
      { id: 'fn-3', title: 'Name', instruction: 'Name the feared outcome in one sentence.', durationSec: 40, phase: 'reflect' },
      { id: 'fn-4', title: 'Look', instruction: 'Look around the room.', durationSec: 30, phase: 'orient' },
      { id: 'fn-5', title: 'Now', instruction: 'Name what is actually happening right now.', durationSec: 40, phase: 'notice' },
      { id: 'fn-6', title: 'Exhale', instruction: 'Exhale slowly.', durationSec: 30, phase: 'exhale' },
      { id: 'fn-7', title: 'Choose', instruction: 'Choose one grounded next action.', durationSec: 30, phase: 'complete' },
    ],
  },
  {
    id: 'resentment-release',
    title: 'Resentment Release',
    subtitle: 'Interrupt repetitive inner arguments',
    description: 'A decompression practice for repetitive resentment and inner arguments.',
    category: 'emotional',
    durationSec: 300,
    intensity: 'medium',
    useCases: ['anger', 'overthinking', 'workStress'],
    tags: ['emotional', 'resentment', 'rumination', 'release'],
    safetyNote: 'This is about noticing the loop, not resolving the conflict right now.',
    beforePrompt: 'How stuck is the inner argument?',
    afterPrompt: 'Has the replay quieted even slightly?',
    fallbackPracticeId: 'room-orientation',
    pack: 'emotional',
    steps: [
      { id: 'rr-1', title: 'Notice', instruction: 'Notice the repeated inner argument.', durationSec: 40, phase: 'notice' },
      { id: 'rr-2', title: 'Name', instruction: 'Say: "My mind is replaying this."', durationSec: 40, phase: 'reflect' },
      { id: 'rr-3', title: 'Feet', instruction: 'Feel both feet on the floor.', durationSec: 40, phase: 'press' },
      { id: 'rr-4', title: 'Jaw', instruction: 'Relax your jaw.', durationSec: 40, phase: 'release' },
      { id: 'rr-5', title: 'Exhale', instruction: 'Exhale slowly.', durationSec: 40, phase: 'exhale' },
      { id: 'rr-6', title: 'Ask', instruction: 'Ask: "Is there an action to take, or is this replay only?"', durationSec: 50, phase: 'reflect' },
      { id: 'rr-7', title: 'Choose', instruction: 'Choose: act, write it down, or let the body rest.', durationSec: 50, phase: 'complete' },
    ],
  },

  // ─── SLEEP PACK (5 practices) ──────────────────────────────────────────────
  {
    id: 'body-heavy',
    title: 'Body Heavy',
    subtitle: 'Progressive heaviness for sleep',
    description: 'A body-scan style practice that invites each part of the body to feel heavy. Based on autogenic training principles. Ideal for bedtime.',
    category: 'sleep',
    durationSec: 240,
    intensity: 'low',
    useCases: ['sleep', 'bodyTension', 'sadness'],
    tags: ['sleep', 'body', 'heaviness', 'autogenic'],
    beforePrompt: 'How restless or activated does your body feel?',
    afterPrompt: 'Does your body feel any heavier or more ready for sleep?',
    fallbackPracticeId: 'sleep-exhale',
    pack: 'sleep',
    steps: [
      { id: 'bod-1', title: 'Position', instruction: 'Lie on your back or side. Close your eyes. No effort needed.', durationSec: 15, phase: 'intro', voiceCue: 'Lie down. Close your eyes.' },
      { id: 'bod-2', title: 'Feet heavy', instruction: 'Bring attention to your feet. Imagine them growing heavy. Sinking into the bed.', durationSec: 30, phase: 'notice', voiceCue: 'Your feet are heavy. Sinking.' },
      { id: 'bod-3', title: 'Legs heavy', instruction: 'Let the heaviness spread to your legs. Thighs, knees, calves. All heavy.', durationSec: 30, phase: 'notice', voiceCue: 'Your legs are heavy now.' },
      { id: 'bod-4', title: 'Hips heavy', instruction: 'Your hips and pelvis are heavy. Sinking. The bed is holding all of you.', durationSec: 25, phase: 'notice', voiceCue: 'Your hips are heavy. Sinking.' },
      { id: 'bod-5', title: 'Belly heavy', instruction: 'Your belly is soft and heavy. No holding. No effort. Just weight.', durationSec: 25, phase: 'notice', voiceCue: 'Belly soft and heavy.' },
      { id: 'bod-6', title: 'Chest heavy', instruction: 'Your chest is heavy. Your breath is slow and effortless.', durationSec: 25, phase: 'notice', voiceCue: 'Chest heavy. Breath slow.' },
      { id: 'bod-7', title: 'Arms heavy', instruction: 'Your arms are heavy. Fingers, hands, forearms, upper arms. All sinking.', durationSec: 25, phase: 'notice', voiceCue: 'Your arms are heavy. Sinking.' },
      { id: 'bod-8', title: 'Head heavy', instruction: 'Your head is heavy on the pillow. Your face is soft. Your jaw is loose.', durationSec: 25, phase: 'notice', voiceCue: 'Head heavy on the pillow.' },
      { id: 'bod-9', title: 'Whole body', instruction: 'Your whole body is heavy. Notice the support beneath you. Let go.', durationSec: 25, phase: 'release', voiceCue: 'Whole body heavy. Let go.' },
      { id: 'bod-10', title: 'Complete', instruction: 'No more effort needed. Rest now.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'long-exhale-for-sleep',
    title: 'Long Exhale for Sleep',
    subtitle: 'Sleep-oriented longer exhale breathing',
    description: 'A sleep-oriented variation of longer exhale breathing.',
    category: 'sleep',
    durationSec: 480,
    intensity: 'low',
    useCases: ['sleep', 'anxiety'],
    tags: ['sleep', 'breath', 'bedtime'],
    safetyNote: 'If controlling the breath feels uncomfortable, return to natural breathing.',
    beforePrompt: 'How awake does your body feel?',
    afterPrompt: 'Does your body feel any heavier?',
    fallbackPracticeId: 'body-heavy',
    breathPattern: { inhaleSec: 4, exhaleSec: 8, cycles: 30 },
    pack: 'sleep',
    steps: [
      { id: 'les-1', title: 'Darken', instruction: 'Let the room be dark or dim.', durationSec: 30, phase: 'intro' },
      { id: 'les-2', title: 'Inhale', instruction: 'Inhale softly.', durationSec: 60, phase: 'inhale' },
      { id: 'les-3', title: 'Exhale', instruction: 'Exhale longer.', durationSec: 80, phase: 'exhale' },
      { id: 'les-4', title: 'Easy', instruction: 'Keep the breath easy.', durationSec: 80, phase: 'exhale' },
      { id: 'les-5', title: 'Reduce', instruction: 'Let each exhale reduce effort by one percent.', durationSec: 80, phase: 'exhale' },
      { id: 'les-6', title: 'Thoughts', instruction: 'If thoughts appear, return to the exhale.', durationSec: 80, phase: 'exhale' },
      { id: 'les-7', title: 'Rest', instruction: 'Stop counting and rest.', durationSec: 70, phase: 'complete' },
    ],
  },
  {
    id: 'pmr-for-sleep',
    title: 'PMR for Sleep',
    subtitle: 'Progressive muscle relaxation for bedtime',
    description: 'A longer progressive muscle relaxation practice for sleep.',
    category: 'sleep',
    durationSec: 600,
    intensity: 'low',
    useCases: ['sleep', 'bodyTension'],
    tags: ['sleep', 'body', 'pmr', 'muscle'],
    safetyNote: 'Do not tense injured or painful areas. Use mild effort only.',
    beforePrompt: 'How much tension is your body holding?',
    afterPrompt: 'Does your body feel any heavier or softer?',
    fallbackPracticeId: 'body-heavy',
    pack: 'sleep',
    steps: [
      { id: 'pms-1', title: 'Settle', instruction: 'Settle lying down.', durationSec: 40, phase: 'intro' },
      { id: 'pms-2', title: 'Feet tense', instruction: 'Tense feet gently, then release.', durationSec: 80, phase: 'press' },
      { id: 'pms-3', title: 'Legs tense', instruction: 'Tense legs gently, then release.', durationSec: 80, phase: 'press' },
      { id: 'pms-4', title: 'Hands tense', instruction: 'Tense hands gently, then release.', durationSec: 80, phase: 'press' },
      { id: 'pms-5', title: 'Shoulders tense', instruction: 'Tense shoulders gently, then release.', durationSec: 80, phase: 'press' },
      { id: 'pms-6', title: 'Face tense', instruction: 'Tense face gently, then release.', durationSec: 80, phase: 'press' },
      { id: 'pms-7', title: 'Whole body', instruction: 'Notice the whole body heavier.', durationSec: 80, phase: 'notice' },
      { id: 'pms-8', title: 'Complete', instruction: 'Let sleep come or not come without forcing.', durationSec: 80, phase: 'complete' },
    ],
  },
  {
    id: 'let-the-day-end',
    title: 'Let the Day End',
    subtitle: 'Release the day before sleep',
    description: 'A cognitive-emotional practice for letting go of the day\'s events before sleep. Helps with rumination and "busy brain" at bedtime.',
    category: 'sleep',
    durationSec: 150,
    intensity: 'low',
    useCases: ['sleep', 'overthinking', 'workStress'],
    tags: ['sleep', 'rumination', 'letting-go', 'bedtime'],
    beforePrompt: 'How much is your mind still replaying the day?',
    afterPrompt: 'Have you been able to let any of it go?',
    fallbackPracticeId: 'sleep-exhale',
    pack: 'sleep',
    steps: [
      { id: 'let-1', title: 'Arrive', instruction: 'The day is over. Whatever happened, it is done. You are in bed. That is enough.', durationSec: 15, phase: 'intro' },
      { id: 'let-2', title: 'Replay', instruction: 'Let the day replay briefly. Not in detail — just the shape of it. Morning, afternoon, evening.', durationSec: 25, phase: 'reflect' },
      { id: 'let-3', title: 'Acknowledge', instruction: 'Acknowledge one thing that was hard. One thing that was okay. Both count.', durationSec: 20, phase: 'reflect' },
      { id: 'let-4', title: 'Release', instruction: 'Imagine placing the entire day on a shelf beside your bed. You can pick it up tomorrow if needed.', durationSec: 20, phase: 'release' },
      { id: 'let-5', title: 'Tomorrow', instruction: 'Tomorrow is not here yet. You do not need to prepare for it right now.', durationSec: 15, phase: 'reflect' },
      { id: 'let-6', title: 'Body', instruction: 'Bring attention to your body. Let it be heavy. Let the bed hold you.', durationSec: 25, phase: 'release' },
      { id: 'let-7', title: 'Permission', instruction: 'Give yourself permission to sleep. You have done enough today.', durationSec: 15, phase: 'reflect' },
      { id: 'let-8', title: 'Complete', instruction: 'The day has ended. Rest now.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'middle-of-night-reset',
    title: 'Middle of the Night Reset',
    subtitle: 'Low-stimulation reset for waking at night',
    description: 'A low-stimulation reset for waking up at night.',
    category: 'sleep',
    durationSec: 300,
    intensity: 'low',
    useCases: ['sleep', 'anxiety', 'overthinking'],
    tags: ['sleep', 'night', 'low-stimulation'],
    safetyNote: 'Keep eyes closed or soft. Minimize light exposure.',
    beforePrompt: 'How awake and activated do you feel?',
    afterPrompt: 'Has your body settled any closer to rest?',
    fallbackPracticeId: 'body-heavy',
    pack: 'sleep',
    steps: [
      { id: 'mon-1', title: 'No clock', instruction: 'Do not check the time if possible.', durationSec: 20, phase: 'intro' },
      { id: 'mon-2', title: 'Eyes soft', instruction: 'Keep the eyes closed or soft.', durationSec: 30, phase: 'notice' },
      { id: 'mon-3', title: 'Body', instruction: 'Notice the body lying down.', durationSec: 40, phase: 'notice' },
      { id: 'mon-4', title: 'Exhale', instruction: 'Exhale slowly.', durationSec: 50, phase: 'exhale' },
      { id: 'mon-5', title: 'Count', instruction: 'Count 5 natural breaths.', durationSec: 60, phase: 'exhale' },
      { id: 'mon-6', title: 'Thoughts', instruction: 'If thoughts come, say: "Not now."', durationSec: 50, phase: 'reflect' },
      { id: 'mon-7', title: 'Support', instruction: 'Return to the feeling of support.', durationSec: 50, phase: 'complete' },
    ],
  },

  // ─── BURNOUT PACK (5 practices) ────────────────────────────────────────────
  {
    id: 'low-energy-check-in',
    title: 'Low Energy Check-In',
    subtitle: 'A gentle check-in when you have nothing left',
    description: 'For when you are depleted but still want to show up for yourself. Asks very little. Offers permission to be exactly where you are.',
    category: 'burnout',
    durationSec: 90,
    intensity: 'low',
    useCases: ['lowEnergy', 'burnout', 'sadness'],
    tags: ['burnout', 'low-energy', 'gentle', 'check-in'],
    beforePrompt: 'You are here. That is already something.',
    afterPrompt: 'You checked in. Even at low energy. That matters.',
    fallbackPracticeId: 'no-force-breathing',
    pack: 'burnout',
    steps: [
      { id: 'low-1', title: 'Arrive', instruction: 'You are here. You showed up. That is enough for now.', durationSec: 10, phase: 'intro' },
      { id: 'low-2', title: 'Body', instruction: 'How does your body feel? Tired? Heavy? Drained? Just notice without judging.', durationSec: 15, phase: 'notice' },
      { id: 'low-3', title: 'Energy', instruction: 'If your energy were a phone battery, what percentage would you be at?', durationSec: 15, phase: 'reflect' },
      { id: 'low-4', title: 'Need', instruction: 'What does your body actually need right now? Water? Rest? Movement? Food?', durationSec: 15, phase: 'reflect' },
      { id: 'low-5', title: 'Permission', instruction: 'Give yourself permission to operate at low capacity. You do not have to be at 100%.', durationSec: 15, phase: 'reflect' },
      { id: 'low-6', title: 'One thing', instruction: 'Can you do one small kind thing for yourself in the next 10 minutes?', durationSec: 10, phase: 'reflect' },
      { id: 'low-7', title: 'Complete', instruction: 'You checked in. At low energy, that takes real effort. You did it.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'no-force-breathing',
    title: 'No-Force Breathing',
    subtitle: 'Breathe without trying to breathe well',
    description: 'A practice for when even breathing exercises feel like too much. This is breathing without technique — just observing what your body does on its own.',
    category: 'burnout',
    durationSec: 120,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy', 'numb'],
    tags: ['burnout', 'gentle', 'no-effort', 'rest'],
    beforePrompt: 'How exhausted are you? Be honest.',
    afterPrompt: 'Did you let yourself rest for a moment? That counts.',
    fallbackPracticeId: 'micro-rest',
    pack: 'burnout',
    steps: [
      { id: 'nof-1', title: 'Nothing', instruction: 'You do not have to do this well. You do not have to do anything. Just be here.', durationSec: 15, phase: 'intro' },
      { id: 'nof-2', title: 'Notice', instruction: 'Notice that your body is breathing on its own. You do not have to help.', durationSec: 20, phase: 'notice' },
      { id: 'nof-3', title: 'Let it', instruction: 'Let your breath be whatever it is. Shallow, uneven, fast, slow. All fine.', durationSec: 25, phase: 'notice' },
      { id: 'nof-4', title: 'No fixing', instruction: 'You are not fixing your breath. You are watching it. That is all.', durationSec: 25, phase: 'notice' },
      { id: 'nof-5', title: 'Exist', instruction: 'For these last seconds, just exist. No productivity. No output. Just being.', durationSec: 25, phase: 'pause' },
      { id: 'nof-6', title: 'Complete', instruction: 'You did not force anything. That is the practice. Well done.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'micro-rest',
    title: 'Micro Rest',
    subtitle: 'Tiny intentional pause',
    description: 'A 60-second permission to do absolutely nothing. Designed for people who never stop, never rest, and feel guilty about pausing.',
    category: 'burnout',
    durationSec: 60,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy', 'workStress'],
    tags: ['burnout', 'rest', 'permission', 'micro'],
    beforePrompt: 'How depleted do you feel right now?',
    afterPrompt: 'Even 60 seconds of rest is rest. You did it.',
    fallbackPracticeId: 'no-force-breathing',
    pack: 'burnout',
    steps: [
      { id: 'mic-1', title: 'Stop', instruction: 'Stop everything. Put down your phone. Close your laptop. Just for 60 seconds.', durationSec: 8, phase: 'intro' },
      { id: 'mic-2', title: 'Lean back', instruction: 'Lean back or recline slightly. Let your body be held by the chair or surface.', durationSec: 10, phase: 'release' },
      { id: 'mic-3', title: 'Eyes', instruction: 'Close your eyes or soften your gaze. Let them rest.', durationSec: 10, phase: 'release' },
      { id: 'mic-4', title: 'Nothing', instruction: 'Do nothing. Think nothing. Produce nothing. Just exist for a few breaths.', durationSec: 20, phase: 'pause' },
      { id: 'mic-5', title: 'Complete', instruction: 'You rested. Even briefly. That matters more than you think.', durationSec: 12, phase: 'complete' },
    ],
  },
  {
    id: 'permission-to-stop',
    title: 'Permission to Stop',
    subtitle: 'Interrupt compulsive pushing',
    description: 'A practice for interrupting compulsive pushing when the system is exhausted.',
    category: 'burnout',
    durationSec: 240,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy', 'overthinking'],
    tags: ['burnout', 'permission', 'rest', 'boundaries'],
    safetyNote: 'Stopping is not failure. It is regulation.',
    beforePrompt: 'How much pressure do you feel to keep going?',
    afterPrompt: 'Has the pressure reduced even slightly?',
    fallbackPracticeId: 'micro-rest',
    pack: 'burnout',
    steps: [
      { id: 'pts-1', title: 'Notice', instruction: 'Notice the pressure to keep going.', durationSec: 35, phase: 'notice' },
      { id: 'pts-2', title: 'Say', instruction: 'Say: "Pushing harder is not the only option."', durationSec: 40, phase: 'reflect' },
      { id: 'pts-3', title: 'Feet', instruction: 'Feel your feet or body support.', durationSec: 35, phase: 'press' },
      { id: 'pts-4', title: 'Breathe', instruction: 'Take one natural breath.', durationSec: 35, phase: 'exhale' },
      { id: 'pts-5', title: 'Ask', instruction: 'Ask: "What actually needs to happen now?"', durationSec: 45, phase: 'reflect' },
      { id: 'pts-6', title: 'Choose', instruction: 'Choose one smaller version of the task, or stop.', durationSec: 50, phase: 'complete' },
    ],
  },
  {
    id: 'one-small-next-step',
    title: 'One Small Next Step',
    subtitle: 'Cut through overwhelm with one micro-action',
    description: 'A cognitive-behavioral micro-practice for when everything feels too big. Helps you identify and commit to just one tiny next step.',
    category: 'burnout',
    durationSec: 90,
    intensity: 'low',
    useCases: ['burnout', 'focus', 'lowEnergy'],
    tags: ['burnout', 'overwhelm', 'action', 'micro-step'],
    beforePrompt: 'How overwhelmed or stuck do you feel?',
    afterPrompt: 'Do you have one small next step? That is enough.',
    fallbackPracticeId: 'micro-rest',
    pack: 'burnout',
    steps: [
      { id: 'one-1', title: 'Acknowledge', instruction: 'It feels like too much. That is valid. You do not need to do it all.', durationSec: 10, phase: 'intro' },
      { id: 'one-2', title: 'Breathe', instruction: 'One slow breath. Inhale. Exhale. Just one.', durationSec: 10, phase: 'exhale' },
      { id: 'one-3', title: 'Ask', instruction: 'Ask yourself: what is the smallest possible next step I could take?', durationSec: 15, phase: 'reflect' },
      { id: 'one-4', title: 'Shrink it', instruction: 'Whatever you thought of — make it smaller. What is the 2-minute version?', durationSec: 15, phase: 'reflect' },
      { id: 'one-5', title: 'Name it', instruction: 'Silently name your one small next step. Just one.', durationSec: 15, phase: 'reflect' },
      { id: 'one-6', title: 'Commit', instruction: 'You do not need to do it all. Just this one thing. That is enough.', durationSec: 15, phase: 'reflect' },
      { id: 'one-7', title: 'Complete', instruction: 'Go do it when you are ready. One step at a time.', durationSec: 10, phase: 'complete' },
    ],
  },
];

// ─── HELPER FUNCTIONS ──────────────────────────────────────────────────────────

export function getPracticeById(id: string): Practice | undefined {
  return practices.find(p => p.id === id);
}

export function getPracticesByCategory(category: PracticeCategory): Practice[] {
  return practices.filter(p => p.category === category);
}

export function getPracticesByPack(pack: Practice['pack']): Practice[] {
  return practices.filter(p => p.pack === pack);
}
