import { Practice, PracticeCategory } from './types';

export const practices: Practice[] = [
  // ─── MVP PACK (10 practices) ───────────────────────────────────────────────
  {
    id: 'long-exhale-reset',
    title: 'Long Exhale Reset',
    subtitle: 'Calm the body with longer exhales',
    description: 'A short breathing reset built around making the exhale slightly longer than the inhale. Useful when the body feels activated, rushed, tense, or overstimulated.',
    category: 'breath',
    durationSec: 120,
    intensity: 'low',
    useCases: ['anxiety', 'workStress', 'quickReset'],
    tags: ['breath', 'calm', 'quick'],
    safetyNote: 'If you feel dizzy or uncomfortable, stop controlling the breath and return to normal breathing.',
    beforePrompt: 'Notice your current stress level before starting.',
    afterPrompt: 'Notice whether anything feels even slightly different.',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    breathPattern: { inhaleSec: 4, exhaleSec: 6, cycles: 10 },
    pack: 'mvp',
    steps: [
      { id: 'lon-1', title: 'Settle', instruction: 'Sit or stand in a comfortable position. Let your shoulders drop slightly. You do not need to breathe perfectly.', durationSec: 15, phase: 'intro' },
      { id: 'lon-2', title: 'Notice', instruction: 'Notice your current breath without changing it yet.', durationSec: 15, phase: 'notice' },
      { id: 'lon-3', title: 'Inhale', instruction: 'Inhale softly for 4 seconds.', durationSec: 20, phase: 'inhale' },
      { id: 'lon-4', title: 'Exhale', instruction: 'Exhale slowly for 6 seconds.', durationSec: 25, phase: 'exhale' },
      { id: 'lon-5', title: 'Repeat', instruction: 'Continue with a soft 4-second inhale and a longer 6-second exhale.', durationSec: 30, phase: 'inhale' },
      { id: 'lon-6', title: 'Release', instruction: 'Let the next exhale be a little slower, without forcing it.', durationSec: 10, phase: 'release' },
      { id: 'lon-7', title: 'Complete', instruction: 'Return to natural breathing. Notice whether anything feels even slightly different.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'cyclic-sigh',
    title: 'Cyclic Sigh',
    subtitle: 'Double inhale, long exhale',
    description: 'A short stress reset using a double inhale followed by a long slow exhale. May help when the body feels activated or tense. Keep it gentle.',
    category: 'breath',
    durationSec: 90,
    intensity: 'low',
    useCases: ['anger', 'anxiety', 'quickReset'],
    tags: ['breath', 'calm', 'fast'],
    safetyNote: 'If you feel light-headed, return to normal breathing immediately.',
    beforePrompt: 'Notice the level of activation in your body right now.',
    afterPrompt: 'Check in — has anything shifted even slightly?',
    fallbackPracticeId: 'long-exhale-reset',
    breathPattern: { inhaleSec: 3, exhaleSec: 6, holdAfterInhaleSec: 1, cycles: 8 },
    pack: 'mvp',
    steps: [
      { id: 'cyc-1', title: 'Settle', instruction: 'Find a comfortable position. Shoulders relaxed.', durationSec: 10, phase: 'intro' },
      { id: 'cyc-2', title: 'First inhale', instruction: 'Inhale deeply through your nose.', durationSec: 10, phase: 'inhale' },
      { id: 'cyc-3', title: 'Second inhale', instruction: 'At the top of that inhale, sip in a little more air through the nose.', durationSec: 5, phase: 'inhale' },
      { id: 'cyc-4', title: 'Long exhale', instruction: 'Exhale slowly and fully through your mouth.', durationSec: 15, phase: 'exhale' },
      { id: 'cyc-5', title: 'Repeat cycle', instruction: 'Double inhale through nose, long exhale through mouth. Repeat at your own pace.', durationSec: 35, phase: 'inhale' },
      { id: 'cyc-6', title: 'Final exhale', instruction: 'One last long exhale. Let your breathing return to normal.', durationSec: 10, phase: 'exhale' },
      { id: 'cyc-7', title: 'Complete', instruction: 'Sit with whatever you notice. No need to label it.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'box-breathing',
    title: 'Box Breathing',
    subtitle: 'Equal inhale, hold, exhale, hold',
    description: 'A structured breathing practice using equal inhale, hold, exhale, and pause phases. Useful before work, meetings, or focused tasks.',
    category: 'breath',
    durationSec: 180,
    intensity: 'low',
    useCases: ['focus', 'anxiety', 'workStress'],
    tags: ['breath', 'focus', 'structured'],
    safetyNote: 'If holding the breath causes discomfort, shorten the hold or skip it entirely.',
    beforePrompt: 'Rate your mental clarity right now.',
    afterPrompt: 'Notice if your mind feels any clearer or calmer.',
    fallbackPracticeId: 'long-exhale-reset',
    breathPattern: { inhaleSec: 4, exhaleSec: 4, holdAfterInhaleSec: 4, holdAfterExhaleSec: 4, cycles: 8 },
    pack: 'mvp',
    steps: [
      { id: 'box-1', title: 'Settle', instruction: 'Sit upright. Rest your hands. Close your eyes if comfortable.', durationSec: 15, phase: 'intro' },
      { id: 'box-2', title: 'Inhale', instruction: 'Inhale through the nose for 4 seconds.', durationSec: 20, phase: 'inhale' },
      { id: 'box-3', title: 'Hold', instruction: 'Hold your breath gently for 4 seconds.', durationSec: 20, phase: 'hold' },
      { id: 'box-4', title: 'Exhale', instruction: 'Exhale through the mouth for 4 seconds.', durationSec: 20, phase: 'exhale' },
      { id: 'box-5', title: 'Hold', instruction: 'Hold at the bottom for 4 seconds.', durationSec: 20, phase: 'pause' },
      { id: 'box-6', title: 'Continue', instruction: 'Repeat the box: inhale 4, hold 4, exhale 4, hold 4. Find a steady rhythm.', durationSec: 70, phase: 'inhale' },
      { id: 'box-7', title: 'Complete', instruction: 'Release the pattern. Breathe naturally. Notice your state.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'five-four-three-two-one-grounding',
    title: '5-4-3-2-1 Grounding',
    subtitle: 'Engage all five senses',
    description: 'A classic grounding technique that uses sensory engagement to bring attention out of spiraling thoughts and back into the present moment. Effective for anxiety, dissociation, and panic.',
    category: 'grounding',
    durationSec: 150,
    intensity: 'low',
    useCases: ['anxiety', 'panicLite', 'numb', 'overthinking'],
    tags: ['grounding', 'senses', 'panic'],
    beforePrompt: 'Notice how disconnected or overwhelmed you feel.',
    afterPrompt: 'Check — do you feel even slightly more present?',
    fallbackPracticeId: 'feet-on-floor',
    pack: 'mvp',
    steps: [
      { id: 'fiv-1', title: 'Settle', instruction: 'Pause wherever you are. You do not need to move or change anything.', durationSec: 10, phase: 'intro' },
      { id: 'fiv-2', title: '5 things you see', instruction: 'Look around and silently name 5 things you can see right now.', durationSec: 30, phase: 'orient' },
      { id: 'fiv-3', title: '4 things you can touch', instruction: 'Notice 4 things you can physically feel — texture, temperature, pressure.', durationSec: 25, phase: 'notice' },
      { id: 'fiv-4', title: '3 things you hear', instruction: 'Listen for 3 sounds. Near or far, loud or quiet.', durationSec: 25, phase: 'notice' },
      { id: 'fiv-5', title: '2 things you smell', instruction: 'Notice 2 scents. If nothing is obvious, bring something close to your nose.', durationSec: 25, phase: 'notice' },
      { id: 'fiv-6', title: '1 thing you taste', instruction: 'Notice 1 taste in your mouth right now.', durationSec: 20, phase: 'notice' },
      { id: 'fiv-7', title: 'Complete', instruction: 'Take a breath. You are here, in this moment.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'feet-on-floor',
    title: 'Feet on Floor',
    subtitle: 'Ground through body contact',
    description: 'A minimal grounding practice focused on physical contact between your feet and the ground. Quick, effective, and works anywhere — sitting or standing.',
    category: 'grounding',
    durationSec: 60,
    intensity: 'low',
    useCases: ['panicLite', 'numb', 'quickReset'],
    tags: ['grounding', 'quick', 'body'],
    beforePrompt: 'Notice how present or disconnected you feel.',
    afterPrompt: 'Do you feel even slightly more grounded?',
    fallbackPracticeId: 'room-orientation',
    pack: 'mvp',
    steps: [
      { id: 'fee-1', title: 'Notice', instruction: 'Feel both feet making contact with the floor or ground beneath you.', durationSec: 10, phase: 'notice' },
      { id: 'fee-2', title: 'Press', instruction: 'Press your feet down gently. Notice the pressure and texture.', durationSec: 15, phase: 'press', haptic: true },
      { id: 'fee-3', title: 'Lift and press', instruction: 'Lift your toes, then press them back down. Notice the shift.', durationSec: 15, phase: 'press' },
      { id: 'fee-4', title: 'Rock', instruction: 'Gently shift your weight side to side. Feel the ground supporting you.', durationSec: 10, phase: 'notice' },
      { id: 'fee-5', title: 'Complete', instruction: 'Stand or sit still. You are here. The ground is holding you.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'room-orientation',
    title: 'Room Orientation',
    subtitle: 'Look around slowly and notice',
    description: 'A slow orientation practice that uses the eyes, head, and environment to reduce inner tunnel vision. May help when feeling disconnected or stuck in thought loops.',
    category: 'grounding',
    durationSec: 90,
    intensity: 'low',
    useCases: ['panicLite', 'numb', 'overthinking', 'shame'],
    tags: ['grounding', 'orienting', 'presence'],
    beforePrompt: 'Notice how trapped or disconnected you feel.',
    afterPrompt: 'Has your sense of the room around you shifted at all?',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    pack: 'mvp',
    steps: [
      { id: 'roo-1', title: 'Pause', instruction: 'Wherever you are, stop and let your eyes rest somewhere neutral.', durationSec: 10, phase: 'intro' },
      { id: 'roo-2', title: 'Look left', instruction: 'Slowly turn your head to the left. Notice what you see without labeling it.', durationSec: 15, phase: 'orient' },
      { id: 'roo-3', title: 'Look right', instruction: 'Now slowly turn your head to the right. Let your eyes land on objects, colors, textures.', durationSec: 15, phase: 'orient' },
      { id: 'roo-4', title: 'Look up', instruction: 'Tilt your gaze upward. Notice the ceiling, sky, or whatever is above.', durationSec: 15, phase: 'orient' },
      { id: 'roo-5', title: 'Look down', instruction: 'Look toward the floor. Notice your feet, the ground, the surface.', durationSec: 15, phase: 'orient' },
      { id: 'roo-6', title: 'Choose one thing', instruction: 'Let your eyes settle on one object that feels neutral or pleasant. Stay with it for a few breaths.', durationSec: 15, phase: 'notice' },
      { id: 'roo-7', title: 'Complete', instruction: 'Notice where you are. This is the room around you.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'jaw-shoulders-release',
    title: 'Jaw & Shoulders Release',
    subtitle: 'Release stored tension in jaw and shoulders',
    description: 'A quick body-based release targeting the two most common tension-holding areas: jaw and shoulders. Uses intentional squeeze and release for fast relief.',
    category: 'body',
    durationSec: 90,
    intensity: 'low',
    useCases: ['bodyTension', 'anger', 'quickReset'],
    tags: ['body', 'tension', 'quick'],
    beforePrompt: 'Notice the tension level in your jaw and shoulders.',
    afterPrompt: 'Check — do your jaw and shoulders feel any different?',
    fallbackPracticeId: 'mini-pmr',
    pack: 'mvp',
    steps: [
      { id: 'jaw-1', title: 'Notice', instruction: 'Bring your attention to your jaw. Is it clenched? Tight? Holding?', durationSec: 10, phase: 'notice' },
      { id: 'jaw-2', title: 'Squeeze jaw', instruction: 'Clench your jaw deliberately for 5 seconds. Feel the tension.', durationSec: 10, phase: 'press', haptic: true },
      { id: 'jaw-3', title: 'Release jaw', instruction: 'Let your jaw fall open slightly. Let your tongue rest. Breathe.', durationSec: 15, phase: 'release' },
      { id: 'jaw-4', title: 'Notice shoulders', instruction: 'Bring attention to your shoulders. Are they raised? Tight?', durationSec: 10, phase: 'notice' },
      { id: 'jaw-5', title: 'Squeeze shoulders', instruction: 'Raise your shoulders toward your ears. Hold for 5 seconds.', durationSec: 10, phase: 'press', haptic: true },
      { id: 'jaw-6', title: 'Release shoulders', instruction: 'Drop your shoulders completely. Let them fall with gravity.', durationSec: 15, phase: 'release' },
      { id: 'jaw-7', title: 'Breathe', instruction: 'Take one slow breath with jaw soft and shoulders low.', durationSec: 15, phase: 'exhale' },
      { id: 'jaw-8', title: 'Complete', instruction: 'Notice the difference. Even a small shift counts.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'mini-pmr',
    title: 'Mini Progressive Muscle Relaxation',
    subtitle: 'Tense and release through body groups',
    description: 'A shortened version of progressive muscle relaxation. Moves through fists, arms, shoulders, and face — squeezing and releasing each group to discharge tension.',
    category: 'body',
    durationSec: 180,
    intensity: 'medium',
    useCases: ['bodyTension', 'anxiety', 'sleep'],
    tags: ['body', 'relaxation', 'tension-release'],
    beforePrompt: 'Notice where tension lives in your body right now.',
    afterPrompt: 'Scan your body — has anything softened?',
    fallbackPracticeId: 'jaw-shoulders-release',
    pack: 'mvp',
    steps: [
      { id: 'min-1', title: 'Settle', instruction: 'Sit or lie down comfortably. Close your eyes if you want.', durationSec: 15, phase: 'intro' },
      { id: 'min-2', title: 'Fists — squeeze', instruction: 'Make fists with both hands. Squeeze them tightly for 5 seconds.', durationSec: 15, phase: 'press', haptic: true },
      { id: 'min-3', title: 'Fists — release', instruction: 'Open your hands slowly. Notice the contrast — the warmth, the ease.', durationSec: 20, phase: 'release' },
      { id: 'min-4', title: 'Arms — squeeze', instruction: 'Tense your arms — biceps, forearms. Hold for 5 seconds.', durationSec: 15, phase: 'press', haptic: true },
      { id: 'min-5', title: 'Arms — release', instruction: 'Let your arms go limp. Feel the release spreading.', durationSec: 20, phase: 'release' },
      { id: 'min-6', title: 'Shoulders — squeeze', instruction: 'Raise shoulders to ears. Squeeze. Hold for 5 seconds.', durationSec: 15, phase: 'press', haptic: true },
      { id: 'min-7', title: 'Shoulders — release', instruction: 'Drop them. Let gravity take them. Breathe out.', durationSec: 20, phase: 'release' },
      { id: 'min-8', title: 'Face — squeeze', instruction: 'Scrunch your whole face — eyes, mouth, forehead. Hold.', durationSec: 15, phase: 'press' },
      { id: 'min-9', title: 'Face — release', instruction: 'Soften everything. Smooth forehead, soft eyes, relaxed mouth.', durationSec: 20, phase: 'release' },
      { id: 'min-10', title: 'Complete', instruction: 'Breathe naturally. Notice your body as a whole — lighter, softer, different.', durationSec: 25, phase: 'complete' },
    ],
  },
  {
    id: 'notice-the-thought',
    title: 'Notice the Thought',
    subtitle: 'Observe thoughts without engaging',
    description: 'A mindfulness micro-practice for thought loops and overthinking. Not about stopping thoughts — just about noticing them as events rather than facts.',
    category: 'mindfulness',
    durationSec: 120,
    intensity: 'low',
    useCases: ['overthinking', 'anxiety', 'shame'],
    tags: ['mindfulness', 'thoughts', 'observe'],
    beforePrompt: 'Notice how loud or fast your thoughts feel right now.',
    afterPrompt: 'Did any space open up between you and your thoughts?',
    fallbackPracticeId: 'room-orientation',
    pack: 'mvp',
    steps: [
      { id: 'not-1', title: 'Settle', instruction: 'Sit still for a moment. You do not need to fix or solve anything right now.', durationSec: 15, phase: 'intro' },
      { id: 'not-2', title: 'Notice', instruction: 'Notice that thoughts are happening. Just acknowledge: "There is a thought."', durationSec: 20, phase: 'notice' },
      { id: 'not-3', title: 'Label', instruction: 'If you can, gently label the thought: planning, worrying, remembering, judging.', durationSec: 20, phase: 'reflect' },
      { id: 'not-4', title: 'Let it pass', instruction: 'Imagine the thought as a cloud passing. You do not need to chase it.', durationSec: 25, phase: 'reflect' },
      { id: 'not-5', title: 'Return', instruction: 'When you get pulled into a thought, gently return to noticing. No judgment.', durationSec: 25, phase: 'notice' },
      { id: 'not-6', title: 'Complete', instruction: 'You are not your thoughts. They come and go. You can just watch.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'physiological-sigh',
    title: 'Physiological Sigh',
    subtitle: 'One breath, immediate reset',
    description: 'The fastest known voluntary calming technique — a single double-inhale followed by an extended exhale. Takes under 30 seconds and is effective even once.',
    category: 'breath',
    durationSec: 45,
    intensity: 'low',
    useCases: ['quickReset', 'anxiety', 'anger'],
    tags: ['breath', 'ultra-quick', 'calming'],
    safetyNote: 'This is a single breath technique. If you feel dizzy, stop and breathe normally.',
    beforePrompt: 'Quick check — how activated do you feel?',
    afterPrompt: 'Even one sigh can shift your state. Notice.',
    fallbackPracticeId: 'long-exhale-reset',
    pack: 'mvp',
    steps: [
      { id: 'phy-1', title: 'Prepare', instruction: 'You only need one breath for this. Stand or sit, however you are.', durationSec: 8, phase: 'intro' },
      { id: 'phy-2', title: 'First inhale', instruction: 'Inhale deeply through your nose.', durationSec: 5, phase: 'inhale' },
      { id: 'phy-3', title: 'Second inhale', instruction: 'At the top, sip in a bit more air through the nose.', durationSec: 4, phase: 'inhale' },
      { id: 'phy-4', title: 'Long exhale', instruction: 'Exhale long and slow through your mouth. Let it all go.', durationSec: 10, phase: 'exhale' },
      { id: 'phy-5', title: 'Repeat', instruction: 'Do it once more: double inhale through nose, long exhale through mouth.', durationSec: 13, phase: 'inhale' },
      { id: 'phy-6', title: 'Complete', instruction: 'Done. That is enough. Notice your state.', durationSec: 5, phase: 'complete' },
    ],
  },

  // ─── WORKDAY PACK (7 practices) ─────────────────────────────────────────────
  {
    id: 'before-meeting-reset',
    title: 'Before Meeting Reset',
    subtitle: 'Quick reset before a stressful meeting',
    description: 'A 90-second practice designed for the gap between meetings or before a difficult conversation. Combines breath and body awareness to shift from reactive to present.',
    category: 'workday',
    durationSec: 90,
    intensity: 'low',
    useCases: ['workStress', 'focus', 'anxiety'],
    tags: ['workday', 'meetings', 'quick'],
    beforePrompt: 'Notice your level of dread or tension about the upcoming situation.',
    afterPrompt: 'Do you feel even slightly more ready?',
    fallbackPracticeId: 'long-exhale-reset',
    pack: 'workday',
    steps: [
      { id: 'bef-1', title: 'Pause', instruction: 'Before you join, pause. Close your laptop or put your phone face-down for a moment.', durationSec: 10, phase: 'intro' },
      { id: 'bef-2', title: 'Feet', instruction: 'Feel your feet on the floor. Press them down once.', durationSec: 10, phase: 'press' },
      { id: 'bef-3', title: 'Exhale', instruction: 'Take one long exhale. Let it be slow and complete.', durationSec: 15, phase: 'exhale' },
      { id: 'bef-4', title: 'Shoulders', instruction: 'Drop your shoulders. Unclench your jaw.', durationSec: 10, phase: 'release' },
      { id: 'bef-5', title: 'Intention', instruction: 'Ask yourself: what do I need from this meeting? Let one word come.', durationSec: 20, phase: 'reflect' },
      { id: 'bef-6', title: 'Breathe', instruction: 'One more slow breath. Inhale presence. Exhale tension.', durationSec: 15, phase: 'exhale' },
      { id: 'bef-7', title: 'Complete', instruction: 'You are as ready as you need to be. Go.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'desk-body-release',
    title: 'Desk Body Release',
    subtitle: 'Release tension from sitting',
    description: 'A body-focused practice designed for people who have been sitting too long. Targets neck, shoulders, wrists, and back without needing to stand.',
    category: 'workday',
    durationSec: 150,
    intensity: 'low',
    useCases: ['bodyTension', 'workStress'],
    tags: ['workday', 'body', 'desk', 'sitting'],
    beforePrompt: 'Notice where your body is holding tension from sitting.',
    afterPrompt: 'Does your body feel any different — even a little?',
    fallbackPracticeId: 'jaw-shoulders-release',
    pack: 'workday',
    steps: [
      { id: 'des-1', title: 'Notice', instruction: 'Without moving yet, scan your body. Where is the tension? Neck? Shoulders? Lower back?', durationSec: 15, phase: 'notice' },
      { id: 'des-2', title: 'Neck rolls', instruction: 'Slowly drop your chin to your chest, then roll your head gently to one side, then the other.', durationSec: 25, phase: 'release' },
      { id: 'des-3', title: 'Shoulder shrug', instruction: 'Raise both shoulders to your ears. Hold 3 seconds. Drop them completely.', durationSec: 20, phase: 'press' },
      { id: 'des-4', title: 'Wrist circles', instruction: 'Circle your wrists slowly — 5 times one way, 5 times the other.', durationSec: 20, phase: 'release' },
      { id: 'des-5', title: 'Spine twist', instruction: 'Sitting tall, gently twist your torso to the left, hold, then to the right.', durationSec: 25, phase: 'release' },
      { id: 'des-6', title: 'Hands press', instruction: 'Press your palms together in front of your chest firmly for 5 seconds, then release.', durationSec: 20, phase: 'press', haptic: true },
      { id: 'des-7', title: 'Settle', instruction: 'Sit back. Take one breath. Let your body settle into a slightly new position.', durationSec: 15, phase: 'release' },
      { id: 'des-8', title: 'Complete', instruction: 'Your body just got a small reset. That counts.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'post-meeting-discharge',
    title: 'Post-Meeting Discharge',
    subtitle: 'Release what the meeting left behind',
    description: 'A quick discharge practice for after a difficult meeting or interaction. Helps prevent residual tension from accumulating through the day.',
    category: 'workday',
    durationSec: 90,
    intensity: 'low',
    useCases: ['workStress', 'anger', 'bodyTension'],
    tags: ['workday', 'discharge', 'post-meeting'],
    beforePrompt: 'Notice what the meeting left in your body.',
    afterPrompt: 'Have you let any of it go?',
    fallbackPracticeId: 'cyclic-sigh',
    pack: 'workday',
    steps: [
      { id: 'pos-1', title: 'Acknowledge', instruction: 'That was something. Acknowledge it without judgment. Something happened.', durationSec: 10, phase: 'intro' },
      { id: 'pos-2', title: 'Body check', instruction: 'Where did that meeting land in your body? Chest? Jaw? Stomach? Just notice.', durationSec: 15, phase: 'notice' },
      { id: 'pos-3', title: 'Shake', instruction: 'Shake your hands loosely for 10 seconds. Shake off what you can.', durationSec: 15, phase: 'release' },
      { id: 'pos-4', title: 'Exhale', instruction: 'Take a deep breath in and let out a big exhale — audible if you can.', durationSec: 15, phase: 'exhale' },
      { id: 'pos-5', title: 'Boundary', instruction: 'Silently say: "That is done. I am here now."', durationSec: 15, phase: 'reflect' },
      { id: 'pos-6', title: 'Ground', instruction: 'Press your feet into the floor. Feel the ground holding you.', durationSec: 10, phase: 'press' },
      { id: 'pos-7', title: 'Complete', instruction: 'Move on when you are ready. You do not have to carry all of it.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'focus-breath',
    title: 'Focus Breath',
    subtitle: 'Sharpen attention with rhythmic breathing',
    description: 'A breath pattern designed to improve concentration and mental clarity. Uses slightly energizing inhales with structured rhythm to sharpen focus.',
    category: 'workday',
    durationSec: 120,
    intensity: 'low',
    useCases: ['focus', 'workStress'],
    tags: ['workday', 'focus', 'breath', 'concentration'],
    beforePrompt: 'How scattered does your attention feel right now?',
    afterPrompt: 'Is your attention any more gathered?',
    fallbackPracticeId: 'box-breathing',
    pack: 'workday',
    steps: [
      { id: 'foc-1', title: 'Settle', instruction: 'Sit upright. Feet flat. Hands resting. Eyes soft or closed.', durationSec: 10, phase: 'intro' },
      { id: 'foc-2', title: 'Notice', instruction: 'Notice where your attention is right now. Scattered? Fuzzy? Racing?', durationSec: 10, phase: 'notice' },
      { id: 'foc-3', title: 'Inhale energy', instruction: 'Inhale for 4 seconds — imagine drawing in focus and clarity.', durationSec: 15, phase: 'inhale' },
      { id: 'foc-4', title: 'Hold', instruction: 'Hold for 2 seconds at the top. A brief pause of stillness.', durationSec: 10, phase: 'hold' },
      { id: 'foc-5', title: 'Exhale release', instruction: 'Exhale for 4 seconds — releasing distraction, fog, noise.', durationSec: 15, phase: 'exhale' },
      { id: 'foc-6', title: 'Rhythm', instruction: 'Continue this rhythm: 4 in, 2 hold, 4 out. Stay with it.', durationSec: 45, phase: 'inhale' },
      { id: 'foc-7', title: 'Complete', instruction: 'Release the pattern. Open your eyes. Bring this clarity to your next task.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'one-small-next-step',
    title: 'One Small Next Step',
    subtitle: 'Cut through overwhelm with one micro-action',
    description: 'A cognitive-behavioral micro-practice for when everything feels too big. Helps you identify and commit to just one tiny next step.',
    category: 'workday',
    durationSec: 90,
    intensity: 'low',
    useCases: ['burnout', 'focus', 'lowEnergy'],
    tags: ['workday', 'overwhelm', 'action', 'micro-step'],
    beforePrompt: 'How overwhelmed or stuck do you feel?',
    afterPrompt: 'Do you have one small next step? That is enough.',
    fallbackPracticeId: 'micro-rest',
    pack: 'workday',
    steps: [
      { id: 'one-1', title: 'Acknowledge', instruction: 'It feels like too much. That is valid. You do not need to do it all.', durationSec: 10, phase: 'intro' },
      { id: 'one-2', title: 'Breathe', instruction: 'One slow breath. Inhale. Exhale. Just one.', durationSec: 10, phase: 'exhale' },
      { id: 'one-3', title: 'Ask', instruction: 'Ask yourself: what is the smallest possible next step I could take?', durationSec: 15, phase: 'reflect' },
      { id: 'one-4', title: 'Shrink it', instruction: 'Whatever you thought of — make it smaller. What is the 2-minute version?', durationSec: 15, phase: 'reflect' },
      { id: 'one-5', title: 'Name it', instruction: 'Silently name your one small next step. Just one.', durationSec: 15, phase: 'reflect' },
      { id: 'one-6', title: 'Commit', instruction: 'You do not need to do it all. Just this one thing. That is enough.', durationSec: 15, phase: 'reflect' },
      { id: 'one-7', title: 'Complete', instruction: 'Go do it when you are ready. One step at a time.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'transition-ritual',
    title: 'Transition Ritual',
    subtitle: 'Mark the shift between work and rest',
    description: 'A practice for the end of the workday or between work blocks. Creates a psychological boundary between "on" mode and rest mode.',
    category: 'workday',
    durationSec: 120,
    intensity: 'low',
    useCases: ['workStress', 'burnout'],
    tags: ['workday', 'boundary', 'transition', 'end-of-day'],
    beforePrompt: 'How carried are you still by work?',
    afterPrompt: 'Have you begun to let the workday go?',
    fallbackPracticeId: 'let-the-day-end',
    pack: 'workday',
    steps: [
      { id: 'tra-1', title: 'Acknowledge', instruction: 'The workday is done — or at least this part. Acknowledge what you did today.', durationSec: 15, phase: 'intro' },
      { id: 'tra-2', title: 'Name it', instruction: 'Silently name one thing you accomplished, even if small.', durationSec: 15, phase: 'reflect' },
      { id: 'tra-3', title: 'Let go', instruction: 'Name one thing you are choosing to leave for tomorrow.', durationSec: 15, phase: 'reflect' },
      { id: 'tra-4', title: 'Body release', instruction: 'Roll your shoulders back. Drop your hands. Exhale.', durationSec: 15, phase: 'release' },
      { id: 'tra-5', title: 'Boundary', instruction: 'Silently say: "Work is done. I am allowed to rest now."', durationSec: 15, phase: 'reflect' },
      { id: 'tra-6', title: 'Sense shift', instruction: 'Notice one non-work thing: a window, a sound, a person, the sky.', durationSec: 20, phase: 'orient' },
      { id: 'tra-7', title: 'Breathe', instruction: 'One deep breath in. Long exhale out. You are off.', durationSec: 15, phase: 'exhale' },
      { id: 'tra-8', title: 'Complete', instruction: 'The transition has happened. Allow it.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'micro-rest',
    title: 'Micro Rest',
    subtitle: 'Tiny intentional rest between tasks',
    description: 'A 60-second permission to do absolutely nothing. Designed for people who never stop, never rest, and feel guilty about pausing.',
    category: 'workday',
    durationSec: 60,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy', 'workStress'],
    tags: ['workday', 'rest', 'permission', 'micro'],
    beforePrompt: 'How depleted do you feel right now?',
    afterPrompt: 'Even 60 seconds of rest is rest. You did it.',
    fallbackPracticeId: 'no-force-breathing',
    pack: 'workday',
    steps: [
      { id: 'mic-1', title: 'Stop', instruction: 'Stop everything. Put down your phone. Close your laptop. Just for 60 seconds.', durationSec: 8, phase: 'intro' },
      { id: 'mic-2', title: 'Lean back', instruction: 'Lean back or recline slightly. Let your body be held by the chair or surface.', durationSec: 10, phase: 'release' },
      { id: 'mic-3', title: 'Eyes', instruction: 'Close your eyes or soften your gaze. Let them rest.', durationSec: 10, phase: 'release' },
      { id: 'mic-4', title: 'Nothing', instruction: 'Do nothing. Think nothing. Produce nothing. Just exist for a few breaths.', durationSec: 20, phase: 'pause' },
      { id: 'mic-5', title: 'Complete', instruction: 'You rested. Even briefly. That matters more than you think.', durationSec: 12, phase: 'complete' },
    ],
  },

  // ─── EMOTIONAL PACK (7 practices) ──────────────────────────────────────────
  {
    id: 'anger-cooling',
    title: 'Anger Cooling',
    subtitle: 'Cool down hot anger without suppressing',
    description: 'A practice for when anger is running hot. Not about pushing it away — about giving it a channel to discharge safely without escalation.',
    category: 'emotional',
    durationSec: 120,
    intensity: 'medium',
    useCases: ['anger', 'bodyTension'],
    tags: ['emotional', 'anger', 'discharge', 'cooling'],
    safetyNote: 'This is not about suppressing anger. It is about not letting it drive your actions. If rage is overwhelming, walk away from the situation first.',
    beforePrompt: 'How hot does the anger feel right now?',
    afterPrompt: 'Has the temperature dropped even one degree?',
    fallbackPracticeId: 'cyclic-sigh',
    pack: 'emotional',
    steps: [
      { id: 'ang-1', title: 'Acknowledge', instruction: 'You are angry. That is real. You do not have to act on it right now.', durationSec: 10, phase: 'intro' },
      { id: 'ang-2', title: 'Hands', instruction: 'Press your palms flat on a surface — desk, wall, thighs. Press hard for 5 seconds.', durationSec: 15, phase: 'press', haptic: true },
      { id: 'ang-3', title: 'Release', instruction: 'Release the press. Shake your hands out loosely.', durationSec: 10, phase: 'release' },
      { id: 'ang-4', title: 'Cold breath', instruction: 'Breathe in through your nose. Exhale slowly through pursed lips — like blowing on hot soup.', durationSec: 20, phase: 'exhale' },
      { id: 'ang-5', title: 'Repeat', instruction: 'Again: press hard, release, shake, exhale through pursed lips.', durationSec: 25, phase: 'press' },
      { id: 'ang-6', title: 'Name it', instruction: 'Silently say: "I am angry about ___." Just name it. Do not solve it.', durationSec: 20, phase: 'reflect' },
      { id: 'ang-7', title: 'Ground', instruction: 'Feel your feet on the ground. You are here. The anger does not own you.', durationSec: 15, phase: 'notice' },
      { id: 'ang-8', title: 'Complete', instruction: 'You chose not to react. That takes strength. The anger will pass.', durationSec: 5, phase: 'complete' },
    ],
  },
  {
    id: 'sadness-grounding',
    title: 'Sadness Grounding',
    subtitle: 'Be with sadness without drowning',
    description: 'A gentle practice for when sadness is present. Not about fixing or fighting it — about being with it safely and knowing it will move.',
    category: 'emotional',
    durationSec: 150,
    intensity: 'low',
    useCases: ['sadness', 'numb', 'lowEnergy'],
    tags: ['emotional', 'sadness', 'gentle', 'grounding'],
    safetyNote: 'If sadness feels unbearable or you are having thoughts of self-harm, please reach out to a crisis helpline or trusted person.',
    beforePrompt: 'How heavy does the sadness feel?',
    afterPrompt: 'Is there any space around the sadness now?',
    fallbackPracticeId: 'feet-on-floor',
    pack: 'emotional',
    steps: [
      { id: 'sad-1', title: 'Acknowledge', instruction: 'Something hurts. You do not have to explain it or fix it right now.', durationSec: 15, phase: 'intro' },
      { id: 'sad-2', title: 'Body', instruction: 'Where do you feel the sadness in your body? Chest? Throat? Eyes? Just notice.', durationSec: 20, phase: 'notice' },
      { id: 'sad-3', title: 'Hand on heart', instruction: 'Place a hand on your chest if that feels okay. Feel the warmth of your own hand.', durationSec: 20, phase: 'press' },
      { id: 'sad-4', title: 'Breathe with it', instruction: 'Breathe gently. Not to fix the sadness — just to be with it.', durationSec: 25, phase: 'exhale' },
      { id: 'sad-5', title: 'Allow', instruction: 'Silently say: "It is okay to feel this." You do not need to be strong right now.', durationSec: 20, phase: 'reflect' },
      { id: 'sad-6', title: 'Anchor', instruction: 'Feel your feet on the ground. The ground is still here. You are still here.', durationSec: 20, phase: 'notice' },
      { id: 'sad-7', title: 'Kindness', instruction: 'What would you say to a friend feeling this? Offer that same kindness to yourself.', durationSec: 20, phase: 'reflect' },
      { id: 'sad-8', title: 'Complete', instruction: 'You stayed with it. That is brave. The sadness will move when it is ready.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'shame-softening',
    title: 'Shame Softening',
    subtitle: 'Gently loosen the grip of shame',
    description: 'A practice for when shame or self-criticism is loud. Uses gentle awareness and self-compassion to create space around the feeling.',
    category: 'emotional',
    durationSec: 150,
    intensity: 'low',
    useCases: ['shame', 'sadness', 'overthinking'],
    tags: ['emotional', 'shame', 'self-compassion', 'softening'],
    safetyNote: 'Shame can feel overwhelming. If it becomes too intense, ground yourself with the 5-4-3-2-1 technique or reach out to someone you trust.',
    beforePrompt: 'How strong is the shame or self-criticism right now?',
    afterPrompt: 'Has the voice softened even a little?',
    fallbackPracticeId: 'room-orientation',
    pack: 'emotional',
    steps: [
      { id: 'sha-1', title: 'Notice', instruction: 'Notice the shame. Where does it live? What is it saying?', durationSec: 15, phase: 'notice' },
      { id: 'sha-2', title: 'Name it', instruction: 'Silently acknowledge: "This is shame." Naming it creates a tiny distance from it.', durationSec: 15, phase: 'reflect' },
      { id: 'sha-3', title: 'Body', instruction: 'Notice where shame lives in your body. Chest? Face? Stomach? Heat? Heaviness?', durationSec: 20, phase: 'notice' },
      { id: 'sha-4', title: 'Breathe toward it', instruction: 'Breathe gently toward that area. Not to fix — just to acknowledge.', durationSec: 20, phase: 'exhale' },
      { id: 'sha-5', title: 'Common humanity', instruction: 'Everyone has felt this. You are not alone in this feeling. It is human.', durationSec: 20, phase: 'reflect' },
      { id: 'sha-6', title: 'Kind word', instruction: 'Offer yourself one kind word or phrase: "I am doing my best." "I am worthy of kindness."', durationSec: 25, phase: 'reflect' },
      { id: 'sha-7', title: 'Hands', instruction: 'Place your hands somewhere comforting — heart, belly, arms crossed in a self-hug.', durationSec: 20, phase: 'press' },
      { id: 'sha-8', title: 'Complete', instruction: 'The shame does not define you. You showed up for yourself. That matters.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'overwhelm-container',
    title: 'Overwhelm Container',
    subtitle: 'Put overwhelming feelings in a container',
    description: 'A visualization practice for when emotions feel too big. Uses the metaphor of placing overwhelming feelings in a container you can return to later.',
    category: 'emotional',
    durationSec: 120,
    intensity: 'low',
    useCases: ['anxiety', 'overthinking', 'burnout'],
    tags: ['emotional', 'overwhelm', 'containment', 'visualization'],
    beforePrompt: 'How overwhelming does everything feel?',
    afterPrompt: 'Does anything feel more contained or manageable?',
    fallbackPracticeId: 'notice-the-thought',
    pack: 'emotional',
    steps: [
      { id: 'ove-1', title: 'Notice', instruction: 'Notice the overwhelm. It is real. It is too much right now. That is okay.', durationSec: 10, phase: 'intro' },
      { id: 'ove-2', title: 'Breathe', instruction: 'Take one slow breath. This is not about solving. It is about containing.', durationSec: 10, phase: 'exhale' },
      { id: 'ove-3', title: 'Imagine', instruction: 'Imagine a strong container — a box, a vault, a chest. Something with a lid.', durationSec: 15, phase: 'reflect' },
      { id: 'ove-4', title: 'Name and place', instruction: 'Name what is overwhelming you — one thing at a time — and imagine placing it in the container.', durationSec: 25, phase: 'reflect' },
      { id: 'ove-5', title: 'Keep going', instruction: 'Continue placing items in. Work stress. That conversation. The to-do list. All of it goes in.', durationSec: 25, phase: 'reflect' },
      { id: 'ove-6', title: 'Close', instruction: 'When ready, close the container. You can return to it later.', durationSec: 15, phase: 'reflect' },
      { id: 'ove-7', title: 'Breathe', instruction: 'Take a breath. Your hands are empty now. Just for this moment.', durationSec: 10, phase: 'exhale' },
      { id: 'ove-8', title: 'Complete', instruction: 'It is still there, but it is contained. You do not have to carry it all at once.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'self-compassion-pause',
    title: 'Self-Compassion Pause',
    subtitle: 'Three steps of self-compassion',
    description: 'Based on Kristin Neff\'s self-compassion framework. Three simple steps: mindfulness, common humanity, and self-kindness. For difficult moments.',
    category: 'emotional',
    durationSec: 120,
    intensity: 'low',
    useCases: ['shame', 'sadness', 'burnout'],
    tags: ['emotional', 'self-compassion', 'kindness'],
    beforePrompt: 'How harshly are you treating yourself right now?',
    afterPrompt: 'Have you softened toward yourself at all?',
    fallbackPracticeId: 'shame-softening',
    pack: 'emotional',
    steps: [
      { id: 'sel-1', title: 'Pause', instruction: 'This is a moment of difficulty. Acknowledge it plainly. Something is hard.', durationSec: 15, phase: 'intro' },
      { id: 'sel-2', title: 'Mindfulness', instruction: 'Say to yourself: "This is suffering." Or: "This hurts." Just name it without drama.', durationSec: 20, phase: 'reflect' },
      { id: 'sel-3', title: 'Common humanity', instruction: 'Say: "Suffering is part of being human." You are not alone in this. Others have felt this too.', durationSec: 20, phase: 'reflect' },
      { id: 'sel-4', title: 'Self-kindness', instruction: 'Place your hand on your heart and say: "May I be kind to myself in this moment."', durationSec: 25, phase: 'press' },
      { id: 'sel-5', title: 'Breathe', instruction: 'Breathe gently. Let the kindness land — even if it feels awkward.', durationSec: 20, phase: 'exhale' },
      { id: 'sel-6', title: 'Complete', instruction: 'You offered yourself compassion. That is not weakness — it is wisdom.', durationSec: 20, phase: 'complete' },
    ],
  },
  {
    id: 'emotional-naming',
    title: 'Emotional Naming',
    subtitle: 'Name it to tame it',
    description: 'A simple affect-labeling practice. Naming emotions clearly may reduce their intensity. Useful when feelings are confusing or overwhelming.',
    category: 'emotional',
    durationSec: 90,
    intensity: 'low',
    useCases: ['anxiety', 'anger', 'numb'],
    tags: ['emotional', 'naming', 'awareness', 'regulation'],
    beforePrompt: 'How confused or overwhelmed do your emotions feel?',
    afterPrompt: 'Do you have a clearer sense of what you are feeling?',
    fallbackPracticeId: 'notice-the-thought',
    pack: 'emotional',
    steps: [
      { id: 'emo-1', title: 'Pause', instruction: 'Pause and turn your attention inward. Something is here.', durationSec: 10, phase: 'intro' },
      { id: 'emo-2', title: 'Body', instruction: 'Scan your body. What sensations are present? Heat, pressure, tightness, heaviness?', durationSec: 15, phase: 'notice' },
      { id: 'emo-3', title: 'Primary emotion', instruction: 'Ask: what am I feeling? Try to name the primary emotion. Angry? Sad? Scared? Ashamed?', durationSec: 15, phase: 'reflect' },
      { id: 'emo-4', title: 'Get specific', instruction: 'Can you get more specific? Not just angry — frustrated? Betrayed? Dismissed?', durationSec: 20, phase: 'reflect' },
      { id: 'emo-5', title: 'Say it', instruction: 'Silently say: "I am feeling ___." Let the label land. You have named it.', durationSec: 15, phase: 'reflect' },
      { id: 'emo-6', title: 'Complete', instruction: 'Naming it does not make it disappear — but it can make it less confusing. That is enough.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'anxiety-wave',
    title: 'Riding the Anxiety Wave',
    subtitle: 'Let anxiety rise and fall naturally',
    description: 'A practice that uses the metaphor of waves to help you sit with anxiety instead of fighting it. Anxiety peaks and passes — this helps you stay present through it.',
    category: 'emotional',
    durationSec: 150,
    intensity: 'medium',
    useCases: ['anxiety', 'panicLite'],
    tags: ['emotional', 'anxiety', 'wave', 'acceptance'],
    safetyNote: 'If anxiety escalates into panic, switch to a grounding practice like 5-4-3-2-1 or feet on floor.',
    beforePrompt: 'How intense is the anxiety wave right now?',
    afterPrompt: 'Has the wave begun to recede? Even slightly?',
    fallbackPracticeId: 'five-four-three-two-one-grounding',
    pack: 'emotional',
    steps: [
      { id: 'anx-1', title: 'Notice', instruction: 'The anxiety is here. Do not fight it. Think of it as a wave — it will peak and pass.', durationSec: 15, phase: 'intro' },
      { id: 'anx-2', title: 'Body', instruction: 'Where is the anxiety in your body? Heart racing? Stomach tight? Chest heavy?', durationSec: 20, phase: 'notice' },
      { id: 'anx-3', title: 'Breathe', instruction: 'Breathe slowly. Not to stop the anxiety — just to be with it. Exhale longer than you inhale.', durationSec: 25, phase: 'exhale' },
      { id: 'anx-4', title: 'Watch', instruction: 'Imagine watching the wave. It is rising. Let it rise. You are not the wave — you are the shore.', durationSec: 25, phase: 'reflect' },
      { id: 'anx-5', title: 'Peak', instruction: 'The wave will peak. It always does. You do not need to do anything. Just be here.', durationSec: 25, phase: 'reflect' },
      { id: 'anx-6', title: 'Recede', instruction: 'Notice — is it shifting? Even slightly? Waves always come back down.', durationSec: 25, phase: 'notice' },
      { id: 'anx-7', title: 'Complete', instruction: 'You rode it. You did not drown. The wave passed — or it is passing. Well done.', durationSec: 15, phase: 'complete' },
    ],
  },

  // ─── SLEEP PACK (4 practices) ──────────────────────────────────────────────
  {
    id: 'sleep-exhale',
    title: 'Sleep Exhale',
    subtitle: 'Long exhales to ease into sleep',
    description: 'A bedtime breathing practice using progressively longer exhales to activate the parasympathetic nervous system and prepare the body for sleep.',
    category: 'sleep',
    durationSec: 180,
    intensity: 'low',
    useCases: ['sleep', 'anxiety'],
    tags: ['sleep', 'breath', 'bedtime', 'parasympathetic'],
    safetyNote: 'If controlling the breath feels uncomfortable, return to natural breathing.',
    beforePrompt: 'How awake or activated does your body feel?',
    afterPrompt: 'Does your body feel any heavier or sleepier?',
    fallbackPracticeId: 'body-heavy',
    pack: 'sleep',
    steps: [
      { id: 'sle-1', title: 'Position', instruction: 'Lie down or recline. Close your eyes. Let your body be heavy.', durationSec: 15, phase: 'intro' },
      { id: 'sle-2', title: 'Natural breath', instruction: 'Breathe naturally for a few breaths. No control yet.', durationSec: 20, phase: 'notice' },
      { id: 'sle-3', title: 'Inhale 4', instruction: 'Inhale softly for 4 seconds.', durationSec: 15, phase: 'inhale' },
      { id: 'sle-4', title: 'Exhale 6', instruction: 'Exhale slowly for 6 seconds. Let the exhale be soft and complete.', durationSec: 20, phase: 'exhale' },
      { id: 'sle-5', title: 'Inhale 4', instruction: 'Inhale for 4 seconds again. Gentle and easy.', durationSec: 15, phase: 'inhale' },
      { id: 'sle-6', title: 'Exhale 8', instruction: 'Now extend the exhale to 8 seconds. Slow, like a deflating balloon.', durationSec: 25, phase: 'exhale' },
      { id: 'sle-7', title: 'Continue', instruction: 'Continue with inhale 4, exhale 8. Let each exhale pull you deeper into rest.', durationSec: 50, phase: 'exhale' },
      { id: 'sle-8', title: 'Complete', instruction: 'Release the pattern. Let the body rest without forcing sleep.', durationSec: 20, phase: 'complete' },
    ],
  },
  {
    id: 'body-heavy',
    title: 'Body Heavy',
    subtitle: 'Progressive heaviness for sleep',
    description: 'A body-scan style practice that invites each part of the body to feel heavy. Based on autogenic training principles. Ideal for bedtime.',
    category: 'sleep',
    durationSec: 240,
    intensity: 'low',
    useCases: ['sleep', 'bodyTension', 'sadness'],
    tags: ['sleep', 'body', 'heaviness', 'autogenic'],
    beforePrompt: 'How restless or activated does your body feel?',
    afterPrompt: 'Does your body feel any heavier or more ready for sleep?',
    fallbackPracticeId: 'sleep-exhale',
    pack: 'sleep',
    steps: [
      { id: 'bod-1', title: 'Position', instruction: 'Lie on your back or side. Close your eyes. No effort needed.', durationSec: 15, phase: 'intro' },
      { id: 'bod-2', title: 'Feet heavy', instruction: 'Bring attention to your feet. Imagine them growing heavy. Sinking into the bed.', durationSec: 30, phase: 'notice' },
      { id: 'bod-3', title: 'Legs heavy', instruction: 'Let the heaviness spread to your legs. Thighs, knees, calves. All heavy.', durationSec: 30, phase: 'notice' },
      { id: 'bod-4', title: 'Hips heavy', instruction: 'Your hips and pelvis are heavy. Sinking. The bed is holding all of you.', durationSec: 25, phase: 'notice' },
      { id: 'bod-5', title: 'Belly heavy', instruction: 'Your belly is soft and heavy. No holding. No effort. Just weight.', durationSec: 25, phase: 'notice' },
      { id: 'bod-6', title: 'Chest heavy', instruction: 'Your chest is heavy. Your breath is slow and effortless.', durationSec: 25, phase: 'notice' },
      { id: 'bod-7', title: 'Arms heavy', instruction: 'Your arms are heavy. Fingers, hands, forearms, upper arms. All sinking.', durationSec: 25, phase: 'notice' },
      { id: 'bod-8', title: 'Head heavy', instruction: 'Your head is heavy on the pillow. Your face is soft. Your jaw is loose.', durationSec: 25, phase: 'notice' },
      { id: 'bod-9', title: 'Whole body', instruction: 'Your whole body is heavy. Notice the support beneath you. Let go.', durationSec: 25, phase: 'release' },
      { id: 'bod-10', title: 'Complete', instruction: 'No more effort needed. Rest now.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'let-the-day-end',
    title: 'Let the Day End',
    subtitle: 'Release the day before sleep',
    description: 'A cognitive-emotional practice for letting go of the day\'s events before sleep. Helps with rumination and "busy brain" at bedtime.',
    category: 'sleep',
    durationSec: 150,
    intensity: 'low',
    useCases: ['sleep', 'overthinking', 'workStress'],
    tags: ['sleep', 'rumination', 'letting-go', 'bedtime'],
    beforePrompt: 'How much is your mind still replaying the day?',
    afterPrompt: 'Have you been able to let any of it go?',
    fallbackPracticeId: 'sleep-exhale',
    pack: 'sleep',
    steps: [
      { id: 'let-1', title: 'Arrive', instruction: 'The day is over. Whatever happened, it is done. You are in bed. That is enough.', durationSec: 15, phase: 'intro' },
      { id: 'let-2', title: 'Replay', instruction: 'Let the day replay briefly. Not in detail — just the shape of it. Morning, afternoon, evening.', durationSec: 25, phase: 'reflect' },
      { id: 'let-3', title: 'Acknowledge', instruction: 'Acknowledge one thing that was hard. One thing that was okay. Both count.', durationSec: 20, phase: 'reflect' },
      { id: 'let-4', title: 'Release', instruction: 'Imagine placing the entire day on a shelf beside your bed. You can pick it up tomorrow if needed.', durationSec: 20, phase: 'release' },
      { id: 'let-5', title: 'Tomorrow', instruction: 'Tomorrow is not here yet. You do not need to prepare for it right now.', durationSec: 15, phase: 'reflect' },
      { id: 'let-6', title: 'Body', instruction: 'Bring attention to your body. Let it be heavy. Let the bed hold you.', durationSec: 25, phase: 'release' },
      { id: 'let-7', title: 'Permission', instruction: 'Give yourself permission to sleep. You have done enough today.', durationSec: 15, phase: 'reflect' },
      { id: 'let-8', title: 'Complete', instruction: 'The day has ended. Rest now.', durationSec: 15, phase: 'complete' },
    ],
  },
  {
    id: 'sleep-body-scan',
    title: 'Sleep Body Scan',
    subtitle: 'Slow scan from head to toe for sleep',
    description: 'A classic body scan adapted for sleep. Moves slowly from head to toes, inviting relaxation in each area. Designed to be boring enough to fall asleep during.',
    category: 'sleep',
    durationSec: 300,
    intensity: 'low',
    useCases: ['sleep', 'bodyTension'],
    tags: ['sleep', 'body-scan', 'relaxation', 'long'],
    beforePrompt: 'How restless is your body right now?',
    afterPrompt: 'Are you feeling sleepier? Let it come.',
    fallbackPracticeId: 'body-heavy',
    pack: 'sleep',
    steps: [
      { id: 'slb-1', title: 'Settle', instruction: 'Lie comfortably. Close your eyes. There is nowhere to go and nothing to do.', durationSec: 20, phase: 'intro' },
      { id: 'slb-2', title: 'Scalp and forehead', instruction: 'Bring attention to your scalp. Your forehead. Let them soften and smooth.', durationSec: 30, phase: 'notice' },
      { id: 'slb-3', title: 'Eyes and jaw', instruction: 'Let your eyes rest deep in their sockets. Let your jaw hang slightly open.', durationSec: 30, phase: 'release' },
      { id: 'slb-4', title: 'Neck and throat', instruction: 'Soften your neck. Your throat. Nothing to say, nothing to hold.', durationSec: 30, phase: 'release' },
      { id: 'slb-5', title: 'Shoulders and arms', instruction: 'Let your shoulders melt into the bed. Arms heavy at your sides.', durationSec: 30, phase: 'release' },
      { id: 'slb-6', title: 'Chest and belly', instruction: 'Feel your breath move your chest and belly. No control. Just watching.', durationSec: 35, phase: 'notice' },
      { id: 'slb-7', title: 'Hips and pelvis', instruction: 'Let your hips relax. Your pelvis sinks into the mattress.', durationSec: 30, phase: 'release' },
      { id: 'slb-8', title: 'Legs', instruction: 'Thighs, knees, calves, shins. All relaxing. All heavy.', durationSec: 35, phase: 'release' },
      { id: 'slb-9', title: 'Feet', instruction: 'Your feet are the last to relax. Toes, soles, heels. Everything soft.', durationSec: 25, phase: 'release' },
      { id: 'slb-10', title: 'Whole body', instruction: 'Your whole body is relaxed. You are a body at rest. Let sleep come.', durationSec: 20, phase: 'release' },
      { id: 'slb-11', title: 'Complete', instruction: 'Nothing left to do. Sleep is welcome here.', durationSec: 15, phase: 'complete' },
    ],
  },

  // ─── BURNOUT PACK (4 practices) ────────────────────────────────────────────
  {
    id: 'no-force-breathing',
    title: 'No-Force Breathing',
    subtitle: 'Breathe without trying to breathe well',
    description: 'A practice for when even breathing exercises feel like too much. This is breathing without technique — just observing what your body does on its own.',
    category: 'burnout',
    durationSec: 120,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy', 'numb'],
    tags: ['burnout', 'gentle', 'no-effort', 'rest'],
    beforePrompt: 'How exhausted are you? Be honest.',
    afterPrompt: 'Did you let yourself rest for a moment? That counts.',
    fallbackPracticeId: 'micro-rest',
    pack: 'burnout',
    steps: [
      { id: 'nof-1', title: 'Nothing', instruction: 'You do not have to do this well. You do not have to do anything. Just be here.', durationSec: 15, phase: 'intro' },
      { id: 'nof-2', title: 'Notice', instruction: 'Notice that your body is breathing on its own. You do not have to help.', durationSec: 20, phase: 'notice' },
      { id: 'nof-3', title: 'Let it', instruction: 'Let your breath be whatever it is. Shallow, uneven, fast, slow. All fine.', durationSec: 25, phase: 'notice' },
      { id: 'nof-4', title: 'No fixing', instruction: 'You are not fixing your breath. You are watching it. That is all.', durationSec: 25, phase: 'notice' },
      { id: 'nof-5', title: 'Exist', instruction: 'For these last seconds, just exist. No productivity. No output. Just being.', durationSec: 25, phase: 'pause' },
      { id: 'nof-6', title: 'Complete', instruction: 'You did not force anything. That is the practice. Well done.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'low-energy-check-in',
    title: 'Low Energy Check-In',
    subtitle: 'A gentle check-in when you have nothing left',
    description: 'For when you are depleted but still want to show up for yourself. Asks very little. Offers permission to be exactly where you are.',
    category: 'burnout',
    durationSec: 90,
    intensity: 'low',
    useCases: ['lowEnergy', 'burnout', 'sadness'],
    tags: ['burnout', 'low-energy', 'gentle', 'check-in'],
    beforePrompt: 'You are here. That is already something.',
    afterPrompt: 'You checked in. Even at low energy. That matters.',
    fallbackPracticeId: 'no-force-breathing',
    pack: 'burnout',
    steps: [
      { id: 'low-1', title: 'Arrive', instruction: 'You are here. You showed up. That is enough for now.', durationSec: 10, phase: 'intro' },
      { id: 'low-2', title: 'Body', instruction: 'How does your body feel? Tired? Heavy? Drained? Just notice without judging.', durationSec: 15, phase: 'notice' },
      { id: 'low-3', title: 'Energy', instruction: 'If your energy were a phone battery, what percentage would you be at?', durationSec: 15, phase: 'reflect' },
      { id: 'low-4', title: 'Need', instruction: 'What does your body actually need right now? Water? Rest? Movement? Food?', durationSec: 15, phase: 'reflect' },
      { id: 'low-5', title: 'Permission', instruction: 'Give yourself permission to operate at low capacity. You do not have to be at 100%.', durationSec: 15, phase: 'reflect' },
      { id: 'low-6', title: 'One thing', instruction: 'Can you do one small kind thing for yourself in the next 10 minutes?', durationSec: 10, phase: 'reflect' },
      { id: 'low-7', title: 'Complete', instruction: 'You checked in. At low energy, that takes real effort. You did it.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'burnout-boundary',
    title: 'Burnout Boundary',
    subtitle: 'Practice saying no to protect energy',
    description: 'A practice for building internal boundaries when burnout has made you unable to say no. Uses reflection and breath to strengthen your permission to protect your energy.',
    category: 'burnout',
    durationSec: 120,
    intensity: 'low',
    useCases: ['burnout', 'workStress'],
    tags: ['burnout', 'boundaries', 'saying-no', 'protection'],
    beforePrompt: 'How overcommitted do you feel?',
    afterPrompt: 'Do you feel any more permission to protect yourself?',
    fallbackPracticeId: 'micro-rest',
    pack: 'burnout',
    steps: [
      { id: 'bur-1', title: 'Notice', instruction: 'Notice the weight of everything you are carrying. Tasks, expectations, requests.', durationSec: 15, phase: 'notice' },
      { id: 'bur-2', title: 'Too much', instruction: 'Acknowledge: it is too much. That is not failure — it is reality.', durationSec: 15, phase: 'reflect' },
      { id: 'bur-3', title: 'One thing', instruction: 'Think of one thing you wish you could say no to. Just one.', durationSec: 15, phase: 'reflect' },
      { id: 'bur-4', title: 'Say no', instruction: 'Silently practice saying no to it. "No." "Not right now." "I cannot."', durationSec: 15, phase: 'reflect' },
      { id: 'bur-5', title: 'Body', instruction: 'Notice how your body feels when you imagine saying no. Relief? Guilt? Both?', durationSec: 15, phase: 'notice' },
      { id: 'bur-6', title: 'Permission', instruction: '"I am allowed to protect my energy. My no is valid."', durationSec: 20, phase: 'reflect' },
      { id: 'bur-7', title: 'Exhale', instruction: 'Take a deep exhale. Release the weight — even a small part of it.', durationSec: 15, phase: 'exhale' },
      { id: 'bur-8', title: 'Complete', instruction: 'You practiced a boundary. That is the first step to having one.', durationSec: 10, phase: 'complete' },
    ],
  },
  {
    id: 'depletion-rest',
    title: 'Depletion Rest',
    subtitle: 'Deep rest for total depletion',
    description: 'A longer practice for deep depletion. Minimal effort, maximum permission to rest. No technique — just presence and gentleness with a body that has given too much.',
    category: 'burnout',
    durationSec: 240,
    intensity: 'low',
    useCases: ['burnout', 'lowEnergy'],
    tags: ['burnout', 'rest', 'depletion', 'recovery', 'long'],
    beforePrompt: 'How depleted are you? This practice asks nothing of you.',
    afterPrompt: 'You rested. Your body needed it. Trust that.',
    fallbackPracticeId: 'no-force-breathing',
    pack: 'burnout',
    steps: [
      { id: 'dep-1', title: 'Lie down', instruction: 'If you can, lie down. If not, recline as much as possible. Close your eyes.', durationSec: 20, phase: 'intro' },
      { id: 'dep-2', title: 'Let go', instruction: 'Let your body be held by whatever surface supports you. Stop holding yourself up.', durationSec: 30, phase: 'release' },
      { id: 'dep-3', title: 'No effort', instruction: 'There is nothing to do here. No technique. No counting. Just existing.', durationSec: 30, phase: 'pause' },
      { id: 'dep-4', title: 'Breathe', instruction: 'Let your body breathe itself. You do not have to manage it.', durationSec: 30, phase: 'notice' },
      { id: 'dep-5', title: 'Permission', instruction: '"I am allowed to rest. I do not have to earn rest. Rest is a right."', durationSec: 25, phase: 'reflect' },
      { id: 'dep-6', title: 'Silence', instruction: 'Rest in silence. Let your mind wander or go blank. Both are fine.', durationSec: 40, phase: 'pause' },
      { id: 'dep-7', title: 'Body', instruction: 'Notice your body. Heavy? Light? Numb? Whatever it is, it is valid.', durationSec: 25, phase: 'notice' },
      { id: 'dep-8', title: 'Gratitude', instruction: 'Thank your body for carrying you this far. It has done so much.', durationSec: 20, phase: 'reflect' },
      { id: 'dep-9', title: 'Complete', instruction: 'When you are ready to move, move slowly. There is no rush. You rested. It counts.', durationSec: 20, phase: 'complete' },
    ],
  },
];

// ─── HELPER FUNCTIONS ──────────────────────────────────────────────────────────

export function getPracticeById(id: string): Practice | undefined {
  return practices.find(p => p.id === id);
}

export function getPracticesByCategory(category: PracticeCategory): Practice[] {
  return practices.filter(p => p.category === category);
}

export function getPracticesByPack(pack: Practice['pack']): Practice[] {
  return practices.filter(p => p.pack === pack);
}
